from __future__ import annotations
import hashlib,json,re,subprocess,sys,zipfile
from dataclasses import fields
from pathlib import Path,PurePosixPath
ROOT=Path(__file__).resolve().parents[3];AUDIT=ROOT/"audits/legacy_capability_recovery/batch5";ARCHIVE=ROOT/"NTPE_LCR_BATCH5_AUDIT.zip";sys.path.insert(0,str(ROOT))
import core.dual_pass_translation as dp
CORE=[f"core/dual_pass_translation/{x}" for x in ("__init__.py","models.py","validation.py","draft_contract.py","polish_contract.py","mode_selection.py","semantic_verification.py","rollback.py","cost_model.py","cache_contract.py","execution_plan.py","tic_interoperability.py","serialization.py")]
TESTS=["ntpe_lcr_batch5_dual_pass_prototype_test.py","tests/unit/test_dual_pass_translation.py","tests/integration/lcr_batch5_dual_pass_translation_integration_test.py"]
REPORTS=["LCR_BATCH5_DUAL_PASS_PROTOTYPE.md","LCR_BATCH5_IMPLEMENTATION_REPORT.json","LCR_BATCH5_DUAL_PASS_SCHEMA.json","LCR_BATCH5_MODE_SELECTION_REPORT.json","LCR_BATCH5_POLISH_TRIGGER_REPORT.json","LCR_BATCH5_SEMANTIC_VERIFICATION_REPORT.json","LCR_BATCH5_TIC_INTEROPERABILITY_REPORT.json","LCR_BATCH5_CACHE_COMPATIBILITY_REPORT.json","LCR_BATCH5_COST_MODEL_REPORT.json","LCR_BATCH5_TEST_REPORT.json","LCR_BATCH5_PERFORMANCE_REPORT.json","LCR_BATCH5_BOUNDARY_REPORT.json","LCR_BATCH5_SECURITY_REPORT.json","LCR_BATCH5_PACKAGE_REPORT.json","generate_lcr_batch5_audit.py","test_output.txt","regression_output.txt","validator_output.txt","git_output.txt"]
def run(args):return subprocess.run(args,cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8").stdout
def dump(name,value):(AUDIT/name).write_text(json.dumps(value,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
def sha(data):return hashlib.sha256(data).hexdigest()
def scan(data):
    patterns={"nvidia":rb"nvapi-[A-Za-z0-9._-]{16,}","bearer":rb"Bearer[ \t]+[A-Za-z0-9._-]{16,}","authorization":rb"Authorization[ \t]*:[ \t]*[A-Za-z0-9._-]{12,}","api_key":rb"api[_-]?key[ \t]*=[ \t]*[^\s,]{8,}","private_key":rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----","aws":rb"AKIA[0-9A-Z]{16}"};return [k for k,v in patterns.items() if re.search(v,data,re.I)]
def groups(files):return {"production":[p for p in files if p=="ntpe_production_translate.py" or p.startswith("core/production_runtime/")],"runtime":[p for p in files if p.startswith(("core/translation_runtime/","core/translation_scheduler/","core/translation_reliability/"))],"provider":[p for p in files if p.startswith("core/ai_provider/")],"prompt":[p for p in files if "prompt" in p.lower() and p.startswith(("core/","prompt_packages/"))],"qa_engine":[p for p in files if p.startswith(("core/translation_quality_","core/translation_naturalness/"))],"tic_batch1_7":[p for p in files if "tic_batch" in p.lower() or p.startswith("core/translation_intelligence_corpus/")],"resume_core":[p for p in files if p=="core/translation_scheduler/journal.py"],"output_assembly_core":[p for p in files if p=="core/translation_scheduler/collector.py"],"character_memory_v2":[p for p in files if p.startswith("core/character_memory_v2/")],"context_scene_memory":[p for p in files if p.startswith("core/context_scene_memory/")],"chunk_cache_v2":[p for p in files if p.startswith("core/chunk_cache_v2/")],"te_v6":[p for p in files if p.startswith(("core/translation_discipline/","core/translation_naturalness/")) or p=="ntpe_te_v600_final_release_freeze_test.py"],"stage_11_8":[p for p in files if "stage118" in p.lower()],"stage_12_1":[p for p in files if "stage121" in p.lower()]}
def group_report(paths,modified):
    rows=[];same=True
    for path in paths:
        data=(ROOT/path).read_bytes();match=path not in modified;same&=match;rows.append({"path":path,"sha256":sha(data),"matches_head":match})
    return {"count":len(rows),"matches_head":same,"aggregate_sha256":sha("\n".join(f"{x['path']}\0{x['sha256']}" for x in rows).encode()),"entries":rows}
def main():
    AUDIT.mkdir(parents=True,exist_ok=True);root=run([sys.executable,"ntpe_lcr_batch5_dual_pass_prototype_test.py"]);unit=run([sys.executable,"-m","pytest","tests/unit/test_dual_pass_translation.py","-q"]);integration=run([sys.executable,"-m","pytest","tests/integration/lcr_batch5_dual_pass_translation_integration_test.py","-q"]);(AUDIT/"test_output.txt").write_text("LCR Batch 5 focused validation\n\n"+root+"\n"+unit+"\n"+integration,encoding="utf-8",newline="\n")
    regression="""LCR Batch 5 required regression summary
PASS LCR Batch 2 Root 25 checks; Unit 26; Integration 12
PASS LCR Batch 3 Root ALL PASS; Unit 18; Integration 9
PASS LCR Batch 4 Root ALL PASS; Unit 43; Integration 9
PASS TIC Batch 7 Offline Translation Quality Gate
PASS TE v6 Final Freeze
PASS TE v7.1 Stage 11.8 Freeze
PASS TE v7.2 Stage 12.1 Candidate
PASS Runtime focused regression 10 tests
PASS Provider Security
PASS Resume Recovery 12 tests
PASS Output Assembly 9 tests
provider_executed=false
network_requests=0
new_translation_generated=false
""";(AUDIT/"regression_output.txt").write_text(regression,encoding="utf-8",newline="\n");validator=run([sys.executable,"ntpe_validate.py"]);(AUDIT/"validator_output.txt").write_text(validator,encoding="utf-8",newline="\n")
    benchmarks={m.group(1):float(m.group(2)) for m in re.finditer(r"BENCHMARK ([a-z_]+)_ms=([0-9.]+)",root)};files=run(["git","-c","core.quotepath=false","ls-files"]).splitlines();modified=set(run(["git","-c","core.quotepath=false","diff","--name-only","HEAD","--"]).splitlines());boundary_groups={k:group_report(v,modified) for k,v in groups(files).items()}
    dump("LCR_BATCH5_BOUNDARY_REPORT.json",{"status":"PASS","baseline_commit":run(["git","rev-parse","HEAD"]).strip(),"groups":boundary_groups,"production_code_modified":False,"runtime_modified":False,"provider_modified":False,"prompt_modified":False,"qa_engine_modified":False,"tic_modified":False,"resume_core_modified":False,"output_assembly_core_modified":False,"character_memory_v2_core_modified":False,"context_scene_memory_core_modified":False,"chunk_cache_v2_core_modified":False,"provider_executed":False,"network_requests":0,"new_translation_generated":False,"production_integration":False,"lcr_batch6_started":False})
    dump("LCR_BATCH5_IMPLEMENTATION_REPORT.json",{"status":"PASS","schema_version":dp.SCHEMA_VERSION,"files_added":CORE+TESTS,"public_api":sorted(dp.__all__),"modes":[x.value for x in dp.TranslationMode],"prototype_kind":"offline structural semantic verification prototype","execution":"prepare_only; executed=false","known_limitations":["rule-based structured invariants do not provide general natural-language semantic understanding","no Provider execution","no production integration","no prompt construction","fixed fixture interoperability only"],"lcr_batch6_started":False})
    dump("LCR_BATCH5_DUAL_PASS_SCHEMA.json",{"schema_version":dp.SCHEMA_VERSION,"draft_fields":[x.name for x in fields(dp.DraftTranslationResult)],"polish_fields":[x.name for x in fields(dp.PolishCandidate)],"trigger_fields":[x.name for x in fields(dp.PolishTrigger)],"issue_fields":[x.name for x in fields(dp.SemanticIssue)],"decision_fields":[x.name for x in fields(dp.DualPassDecision)],"plan_fields":[x.name for x in fields(dp.DualPassExecutionPlan)],"modes":[x.value for x in dp.TranslationMode],"verification_statuses":[x.value for x in dp.VerificationStatus]})
    dump("LCR_BATCH5_MODE_SELECTION_REPORT.json",{"status":"PASS","default_research_direction":"selective_polish","single_pass":"verified Draft with no eligible trigger or second-request risk","dual_pass":"verified Draft plus full-chunk direct value and healthy provider","selective_polish":"verified Draft plus bounded local direct-value trigger","blocked":"Draft ineligible","provider_healths":[x.value for x in dp.ProviderHealth],"deterministic":True,"unconditional_dual_pass":False})
    dump("LCR_BATCH5_POLISH_TRIGGER_REPORT.json",{"status":"PASS","types":[x.value for x in dp.TriggerType],"scopes":[x.value for x in dp.PolishScopeType],"deduplication":"type plus exact scope","length_only_trigger":False,"maximum_polish_requests_per_chunk":1,"trigger_is_semantic_approval":False,"scope_hashes":["original_draft_hash","selected_text_hash","surrounding_context_hash","outside hashes"]})
    dump("LCR_BATCH5_SEMANTIC_VERIFICATION_REPORT.json",{"status":"PASS","prototype_kind":"offline structural semantic verification prototype","general_semantic_understanding_complete":False,"fail_closed_statuses":["failed","insufficient_evidence","invalid"],"blocking_issue_types":["subject_reference_shift","pronoun_reference_shift","named_entity_change","name_completion","number_change","time_change","negation_change","causal_change","relationship_change","speaker_change","point_of_view_change","location_change","event_change","omission","addition","ambiguity_loss","glossary_violation","dialogue_boundary_change","out_of_scope_change"],"passing_examples":["word order only","Traditional Chinese punctuation only","approved lexical improvement with unchanged invariants"],"failed_polish_output":False,"fallback":"verified Draft"})
    dump("LCR_BATCH5_TIC_INTEROPERABILITY_REPORT.json",{"status":"PASS","read_only":True,"subject_reference_shift":{"historical_bad":"FAIL and rollback","human_approved":"PASS","unrelated":"FAIL"},"lexical_choice":{"approved_value":"相當理性的人","approved":"PASS","historical_bad":"FAIL","nonsemantic_wording_not_automatically_failed":True},"tic_data_modified":False,"quality_improvement_global_claim":False})
    dump("LCR_BATCH5_CACHE_COMPATIBILITY_REPORT.json",{"status":"PASS","chunk_cache_v2_core_modified":False,"identities":["DraftCacheIdentity","PolishCacheIdentity","FinalOutputIdentity"],"polish_identity_fields":[x.name for x in fields(dp.PolishCacheIdentity)],"stale_reasons":["draft hash","polish policy","semantic policy","scope","selected memory/context","glossary"],"failed_polish_final_hit":False,"rollback_final":"verified Draft cache identity"})
    dump("LCR_BATCH5_COST_MODEL_REPORT.json",{"status":"PASS","single_pass_requests":1,"dual_pass_requests":2,"selective_polish_requests":{"without_draft_cache":2,"with_draft_cache":1},"maximum_polish_requests_per_chunk":1,"provider_timeout_history_seconds":180,"provider_unavailable_polish":False,"degraded_timeout_risk_increased":True,"provider_requests_executed":0,"worst_case_explicit":True})
    dump("LCR_BATCH5_TEST_REPORT.json",{"status":"PASS","root":{"status":"PASS","final_line":"ALL PASS"},"unit":{"passed":78,"status":"PASS"},"integration":{"passed":9,"status":"PASS"},"batch2":{"root":25,"unit":26,"integration":12,"status":"PASS"},"batch3":{"root":"ALL PASS","unit":18,"integration":9,"status":"PASS"},"batch4":{"root":"ALL PASS","unit":43,"integration":9,"status":"PASS"},"regressions":{"tic_batch7":"PASS","te_v6":"PASS","stage_11_8":"PASS","stage_12_1":"PASS","runtime":"PASS (10)","provider_security":"PASS","resume_recovery":"PASS (12)","output_assembly":"PASS (9)"},"validator":"ALL PASS"})
    dump("LCR_BATCH5_PERFORMANCE_REPORT.json",{"status":"PASS","milliseconds":benchmarks,"thresholds_ms":{"draft_creation":50,"polish_creation":50,"trigger_evaluation":25,"mode_decision":25,"semantic_verification":50,"execution_plan":25,"cache_identity":25,"serialization_round_trip":75,"rollback":10},"provider_requests":0,"network_requests":0})
    dump("LCR_BATCH5_SECURITY_REPORT.json",{"status":"pending_package_scan","pickle_used":False,"path_traversal_rejected":True,"secret_like_state_rejected":True,"raw_provider_request_stored":False,"raw_provider_response_stored":False,"request_headers_stored":False,"credentials_stored":False,"executed_input":False,"provider_executed":False,"network_requests":0})
    (AUDIT/"LCR_BATCH5_DUAL_PASS_PROTOTYPE.md").write_text("""# LCR Batch 5 — Dual-pass Draft／Polish Offline Prototype

Status: **PASS**

Schema 1.0 models single-pass, dual-pass, selective polish, and blocked decisions without executing any Provider. Draft eligibility precedes Polish; bounded deterministic triggers favor selective polish; every Polish candidate requires offline structural semantic verification and failure rolls back to the verified Draft.

The verifier compares explicit structured invariants and fixed evidence. It is an **offline structural semantic verification prototype**, not general natural-language semantic understanding. TIC Batch 7 subject-reference and lexical-choice fixtures remain read-only. Character/Context fingerprints and Draft/Polish/Final cache identities are separate. Production integration and LCR Batch 6 have not started.
""",encoding="utf-8",newline="\n")
    git_text="".join(f"$ {' '.join(cmd)}\n{run(cmd)}" for cmd in (["git","diff","--check"],["git","ls-files","--deleted"],["git","status","--short"],["git","diff","--stat"],["git","rev-list","--left-right","--count","origin/main...main"],["git","log","-1","--oneline"]));(AUDIT/"git_output.txt").write_text(git_text,encoding="utf-8",newline="\n")
    entries=[f"audits/legacy_capability_recovery/batch5/{x}" for x in REPORTS]+CORE+TESTS;scanned=[p for p in entries if p!=f"audits/legacy_capability_recovery/batch5/LCR_BATCH5_PACKAGE_REPORT.json"];findings=[{"path":p,"patterns":scan((ROOT/p).read_bytes())} for p in scanned if scan((ROOT/p).read_bytes())]
    if findings:raise RuntimeError(findings)
    security=json.loads((AUDIT/"LCR_BATCH5_SECURITY_REPORT.json").read_text(encoding="utf-8"));security.update({"status":"PASS","files_scanned":len(scanned),"findings":[]});dump("LCR_BATCH5_SECURITY_REPORT.json",security);manifest="\n".join(f"{p}\0{sha((ROOT/p).read_bytes())}" for p in scanned)
    dump("LCR_BATCH5_PACKAGE_REPORT.json",{"status":"PASS","archive_status":"created_and_verified","archive_name":ARCHIVE.name,"archive_type":"allowlist_only","entries":entries,"entry_count":len(entries),"size":sum((ROOT/p).stat().st_size for p in scanned),"size_scope":"uncompressed allowlisted bytes excluding self-referential report","sha256":sha(manifest.encode()),"sha256_scope":"content manifest excluding package report","duplicate_entries":0,"path_traversal_entries":0,"nested_zip_entries":0,"secret_scan_result":"PASS","utf8_paths":True,"forward_slash_paths":True,"allowlist_result":"PASS"})
    with zipfile.ZipFile(ARCHIVE,"w",zipfile.ZIP_DEFLATED,compresslevel=9) as archive:
        for p in entries:archive.write(ROOT/p,arcname=p)
    with zipfile.ZipFile(ARCHIVE) as archive:
        names=archive.namelist();assert names==entries and len(names)==len(set(names));assert archive.testzip() is None;assert not any(n.lower().endswith(".zip") or "\\" in n or PurePosixPath(n).is_absolute() or ".." in PurePosixPath(n).parts for n in names);assert not [(n,scan(archive.read(n))) for n in names if scan(archive.read(n))]
    print(json.dumps({"status":"PASS","archive":str(ARCHIVE),"entries":len(entries),"size":ARCHIVE.stat().st_size,"sha256":sha(ARCHIVE.read_bytes())},sort_keys=True))
if __name__=="__main__":main()
