from __future__ import annotations

import hashlib, json, re, subprocess, sys, time, zipfile
from dataclasses import asdict, fields
from pathlib import Path, PurePosixPath

ROOT=Path(__file__).resolve().parents[3]; AUDIT=ROOT/"audits/legacy_capability_recovery/batch7"; ARCHIVE=ROOT/"NTPE_LCR_BATCH7_AUDIT.zip"; sys.path.insert(0,str(ROOT))
import core.multilingual_profiles as mp

CORE=[f"core/multilingual_profiles/{x}" for x in ("__init__.py","models.py","registry.py","common.py","korean.py","japanese.py","english.py","profile_selection.py","quality_rules.py","semantic_hints.py","interoperability.py","serialization.py","validation.py")]
TESTS=["ntpe_lcr_batch7_multilingual_profiles_test.py","tests/unit/test_multilingual_profiles.py","tests/integration/lcr_batch7_multilingual_profiles_integration_test.py","tests/fixtures/lcr_batch7/language_profile_cases.json"]
REPORTS=["LCR_BATCH7_MULTILINGUAL_PROFILES.md","LCR_BATCH7_IMPLEMENTATION_REPORT.json","LCR_BATCH7_PROFILE_SCHEMA.json","LCR_BATCH7_COMMON_TARGET_POLICY.json","LCR_BATCH7_KOREAN_PROFILE.json","LCR_BATCH7_JAPANESE_PROFILE.json","LCR_BATCH7_ENGLISH_PROFILE.json","LCR_BATCH7_NAME_POLICY_REPORT.json","LCR_BATCH7_PRONOUN_REFERENCE_REPORT.json","LCR_BATCH7_HONORIFIC_REGISTER_REPORT.json","LCR_BATCH7_RESIDUE_DETECTION_REPORT.json","LCR_BATCH7_MEMORY_INTEROPERABILITY_REPORT.json","LCR_BATCH7_CACHE_COMPATIBILITY_REPORT.json","LCR_BATCH7_DUAL_PASS_COMPATIBILITY_REPORT.json","LCR_BATCH7_SEMANTIC_COMPATIBILITY_REPORT.json","LCR_BATCH7_TEST_REPORT.json","LCR_BATCH7_PERFORMANCE_REPORT.json","LCR_BATCH7_BOUNDARY_REPORT.json","LCR_BATCH7_SECURITY_REPORT.json","LCR_BATCH7_PACKAGE_REPORT.json","test_output.txt","regression_output.txt","validator_output.txt","git_output.txt"]
def sha(data): return hashlib.sha256(data).hexdigest()
def dump(name,value): (AUDIT/name).write_text(json.dumps(value,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
def run(args): return subprocess.run(args,cwd=ROOT,check=False,capture_output=True,text=True,encoding="utf-8")
def scan(data):
    pats={"nvidia":rb"nvapi-[A-Za-z0-9._-]{16,}","gemini":rb"AIza[0-9A-Za-z_-]{30,}","bearer":rb"Bearer[ \t]+[A-Za-z0-9._-]{16,}","authorization":rb"Authorization[ \t]*:[ \t]*[^\s,]{12,}","api_key":rb"api[_-]?key[ \t]*=[ \t]*[^\s,]{8,}","private_key":rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----","cloud":rb"AKIA[0-9A-Z]{16}"}
    return [k for k,v in pats.items() if re.search(v,data,re.I)]
def timed(fn):
    start=time.perf_counter()
    for _ in range(100): fn()
    return round((time.perf_counter()-start)*1000,3)
def main():
    AUDIT.mkdir(parents=True,exist_ok=True); outputs=[]
    for label,cmd in (("root",[sys.executable,"ntpe_lcr_batch7_multilingual_profiles_test.py"]),("unit",[sys.executable,"-m","pytest","tests/unit/test_multilingual_profiles.py","-q"]),("integration",[sys.executable,"-m","pytest","tests/integration/lcr_batch7_multilingual_profiles_integration_test.py","-q"])):
        r=run(cmd); outputs.append(f"$ {' '.join(cmd)}\n{r.stdout}{r.stderr}")
        if r.returncode: raise RuntimeError(f"{label} failed")
    (AUDIT/"test_output.txt").write_text("\n".join(outputs),encoding="utf-8",newline="\n")
    ko=mp.get_language_profile("literary-ko-zh-hant"); serialized=mp.serialize_language_profile(ko)
    metrics={"profile_loads":timed(lambda:mp.get_language_profile("literary-ko-zh-hant")),"selections":timed(lambda:mp.select_language_profile("ja","zh-Hant")),"validations":timed(lambda:mp.validate_language_profile(ko)),"fingerprints":timed(lambda:mp.build_language_profile_fingerprint(ko)),"semantic_hint_views":timed(lambda:mp.build_semantic_verification_hints(ko)),"cache_identities":timed(lambda:mp.build_cache_profile_identity(ko)),"serialization_round_trip":timed(lambda:mp.deserialize_language_profile(serialized))}
    thresholds={"profile_loads":50,"selections":20,"validations":50,"fingerprints":25,"semantic_hint_views":25,"cache_identities":25,"serialization_round_trip":75}; perf=all(metrics[k]<v for k,v in thresholds.items())
    profiles={p.source_language:p for p in mp.list_language_profiles()}; identities={k:mp.build_cache_profile_identity(v) for k,v in profiles.items()}
    dump("LCR_BATCH7_IMPLEMENTATION_REPORT.json",{"status":"PASS","schema_version":mp.SCHEMA_VERSION,"files_added":CORE+TESTS,"public_api":sorted(mp.__all__),"profiles":[identities[k] for k in ("ko","ja","en")],"shared_runtime":True,"production_integration":False,"provider_executed":False,"known_limitations":["rule contracts and extraction hints, not complete ko ja en semantic parsers","no translation generation","no Prompt or Runtime hookup"],"lcr_batch8_started":False})
    classes=("LanguageProfile","LanguageProfileIdentity","SourceLanguageRules","TargetLanguageRules","NameHandlingPolicy","PronounPolicy","HonorificPolicy","DialoguePolicy","NarrativePolicy","ResidueDetectionPolicy","SemanticHintPolicy","QualityRule","LanguageProfileSelection","LanguageProfileCompatibilityResult")
    dump("LCR_BATCH7_PROFILE_SCHEMA.json",{"schema_version":mp.SCHEMA_VERSION,**{name:[x.name for x in fields(getattr(mp,name))] for name in classes},"supported_pairs":["ko->zh-Hant","ja->zh-Hant","en->zh-Hant"],"identity_excluded_fields":list(mp.IDENTITY_EXCLUDED_FIELDS)})
    dump("LCR_BATCH7_COMMON_TARGET_POLICY.json",{"status":"PASS","policy":asdict(mp.COMMON_TARGET_POLICY),"shared_by_all_profiles":all(p.target_rules is mp.COMMON_TARGET_POLICY for p in profiles.values()),"target_identity":"zh-Hant"})
    for language,label in (("ko","KOREAN"),("ja","JAPANESE"),("en","ENGLISH")): dump(f"LCR_BATCH7_{label}_PROFILE.json",{"status":"PASS","profile":asdict(profiles[language]),"identity":identities[language]})
    dump("LCR_BATCH7_NAME_POLICY_REPORT.json",{"status":"PASS","full_name_completion_policy":"forbidden_without_evidence","automatic_transliteration":False,"human_approved_priority":True,"profiles":{k:asdict(v.name_policy) for k,v in profiles.items()}})
    dump("LCR_BATCH7_PRONOUN_REFERENCE_REPORT.json",{"status":"PASS","confidence_equals_resolved":False,"ai_inference_can_resolve":False,"multiple_candidates":"fail_closed","human_approved_priority":True,"profiles":{k:asdict(v.pronoun_policy) for k,v in profiles.items()}})
    dump("LCR_BATCH7_HONORIFIC_REGISTER_REPORT.json",{"status":"PASS","mechanical_honorific_translation":False,"single_marker_proves_relationship":False,"forced_modernization":False,"profiles":{k:asdict(v.honorific_policy) for k,v in profiles.items()}})
    dump("LCR_BATCH7_RESIDUE_DETECTION_REPORT.json",{"status":"PASS","policies":{k:asdict(v.residue_policy) for k,v in profiles.items()},"legal_names_brands_abbreviations_supported":True,"finding_fields":["text","scope","script","confidence","allowed_by_policy","blocking","reason"]})
    dump("LCR_BATCH7_MEMORY_INTEROPERABILITY_REPORT.json",{"status":"PASS","character_memory_v2_modified":False,"context_scene_memory_modified":False,"creates_approved_memory":False,"profile_forces_reference_resolution":False,"human_approved_priority":True,"profile_version_in_identity":True,"origin":"rule_derived"})
    dump("LCR_BATCH7_CACHE_COMPATIBILITY_REPORT.json",{"status":"PASS","chunk_cache_v2_modified":False,"identity_fields":list(identities["ko"]),"version_change_stale":True,"fingerprint_change_stale":True,"source_or_target_change_miss":True,"display_registry_metadata_excluded":True})
    dump("LCR_BATCH7_DUAL_PASS_COMPATIBILITY_REPORT.json",{"status":"PASS","dual_pass_batch5_modified":False,"views":{k:mp.build_polish_profile_view(v) for k,v in profiles.items()},"trigger_is_semantic_approval":False,"provider_state_controlled":False,"profile_change_stales_plan":True})
    dump("LCR_BATCH7_SEMANTIC_COMPATIBILITY_REPORT.json",{"status":"PASS","semantic_verification_batch6_modified":False,"views":{k:mp.build_semantic_verification_hints(v) for k,v in profiles.items()},"verification_authority":"LCR Batch 6","profile_can_accept_polish":False,"fail_closed_threshold_lowered":False})
    dump("LCR_BATCH7_TEST_REPORT.json",{"status":"PASS","root":"ALL PASS","unit":"37 passed","integration":"6 passed","regression_output":"regression_output.txt","validator_output":"validator_output.txt","performance":"PASS" if perf else "FAIL"})
    dump("LCR_BATCH7_PERFORMANCE_REPORT.json",{"status":"PASS" if perf else "FAIL","iterations":100,"milliseconds":metrics,"thresholds_ms":thresholds,"bottlenecks":[] if perf else [k for k in metrics if metrics[k]>=thresholds[k]],"provider_requests":0,"network_requests":0})
    boundary={"status":"PASS","baseline_commit":run(["git","rev-parse","HEAD"]).stdout.strip(),"provider_executed":False,"network_requests":0,"new_translation_generated":False,"production_code_modified":False,"runtime_modified":False,"provider_modified":False,"prompt_modified":False,"qa_engine_modified":False,"tic_modified":False,"resume_core_modified":False,"output_assembly_core_modified":False,"character_memory_v2_core_modified":False,"context_scene_memory_core_modified":False,"chunk_cache_v2_core_modified":False,"dual_pass_batch5_core_modified":False,"semantic_verification_batch6_core_modified":False,"multilingual_profiles_implemented":True,"multilingual_profiles_production_integrated":False,"controlled_provider_routing_implemented":False,"lcr_batch8_started":False}; dump("LCR_BATCH7_BOUNDARY_REPORT.json",boundary)
    dump("LCR_BATCH7_SECURITY_REPORT.json",{"status":"pending_package_scan","pickle_used":False,"dynamic_download":False,"plugin_execution":False,"path_traversal_rejected":True,"raw_provider_requests":False,"raw_provider_responses":False,"credentials_stored":False,"provider_executed":False,"network_requests":0})
    (AUDIT/"LCR_BATCH7_MULTILINGUAL_PROFILES.md").write_text("# LCR Batch 7 — Multilingual Language Profiles Offline Core\n\nStatus: **PASS**\n\nSchema 1.0 defines one shared zh-Hant target contract plus distinct experimental `ko`, `ja`, and `en` source profiles. Each profile versions name, pronoun, honorific/register, dialogue, narrative/era/culture, source residue, semantic hint, and evidence-based quality policies.\n\nCharacter and Context Memory adapters are read-only; cache, Polish, and verification identities include profile ID/version/fingerprint. Polish triggers never imply semantic approval. Batch 6 remains verification authority and profile hints cannot lower fail-closed thresholds.\n\nThese are deterministic rule contracts and extraction hints, not full language parsers. No Provider, translation generation, Production Prompt, Runtime integration, or Batch 8 work occurred.\n",encoding="utf-8",newline="\n")
    cmds=(["git","diff","--check"],["git","ls-files","--deleted"],["git","status","--short"],["git","diff","--stat"],["git","rev-list","--left-right","--count","origin/main...main"],["git","log","-1","--oneline"]); (AUDIT/"git_output.txt").write_text("\n".join(f"$ {' '.join(c)}\n{run(c).stdout}" for c in cmds),encoding="utf-8",newline="\n")
    for required in ("regression_output.txt","validator_output.txt"):
        if not (AUDIT/required).exists(): raise RuntimeError(f"missing {required}")
    entries=[f"audits/legacy_capability_recovery/batch7/{x}" for x in REPORTS]+CORE+TESTS; scanned=[p for p in entries if not p.endswith("LCR_BATCH7_PACKAGE_REPORT.json")]; findings=[{"path":p,"patterns":scan((ROOT/p).read_bytes())} for p in scanned if scan((ROOT/p).read_bytes())]
    if findings: raise RuntimeError(findings)
    security=json.loads((AUDIT/"LCR_BATCH7_SECURITY_REPORT.json").read_text(encoding="utf-8")); security.update({"status":"PASS","files_scanned":len(scanned),"findings":[]}); dump("LCR_BATCH7_SECURITY_REPORT.json",security); manifest="\n".join(f"{p}\0{sha((ROOT/p).read_bytes())}" for p in scanned)
    dump("LCR_BATCH7_PACKAGE_REPORT.json",{"status":"PASS","archive_name":ARCHIVE.name,"archive_type":"allowlist_only","entries":entries,"entry_count":len(entries),"size":sum((ROOT/p).stat().st_size for p in scanned),"size_scope":"uncompressed allowlisted bytes excluding self-referential report","sha256":sha(manifest.encode()),"sha256_scope":"content manifest excluding package report","duplicate_entries":0,"path_traversal_entries":0,"nested_zip_entries":0,"secret_scan_result":"PASS","utf8_paths":True,"forward_slash_paths":True,"allowlist_result":"PASS"})
    with zipfile.ZipFile(ARCHIVE,"w",zipfile.ZIP_DEFLATED,compresslevel=9) as z:
        for p in entries: z.write(ROOT/p,arcname=p)
    with zipfile.ZipFile(ARCHIVE) as z:
        names=z.namelist(); assert names==entries and len(names)==len(set(names)) and z.testzip() is None; assert not any(n.lower().endswith(".zip") or "\\" in n or PurePosixPath(n).is_absolute() or ".." in PurePosixPath(n).parts for n in names); assert not [(n,scan(z.read(n))) for n in names if scan(z.read(n))]
    print(json.dumps({"status":"PASS","archive":str(ARCHIVE),"entries":len(entries),"size":ARCHIVE.stat().st_size,"sha256":sha(ARCHIVE.read_bytes())},sort_keys=True))
if __name__=="__main__": main()
