from __future__ import annotations
import ast,json,subprocess
from pathlib import Path
import core.dual_pass_translation as dp
ROOT=Path(__file__).resolve().parents[2];T0="2026-07-16T00:00:00Z";FIXTURES=json.loads((ROOT/"artifacts/tic_batch7/OFFLINE_QUALITY_GATE_FIXTURES.json").read_text(encoding="utf-8"))["items"]
def fixture(name):return next(x for x in FIXTURES if x["fixture_id"]==name)
def inv(subject="他=遠方男人",units=("u1","u2"),**changes):
    value={"subject_references":[subject],"pronoun_references":[subject],"named_entities":["鄭泰義"],"numbers":[],"times":[],"negations":["不"],"causal_links":[],"relationships":[],"speakers":[],"point_of_view":"third_person","locations":[],"events":["理解"],"ambiguity_markers":[],"dialogue_boundaries":[],"glossary_terms":{},"content_units":list(units)};value.update(changes);return value
def draft(text,semantic=None):return dp.create_draft_result(draft_id="draft-tic",document_id="doc-tic",chunk_index=1,source_hash=dp.sha(fixture("B7-SUBJECT-APPROVED")["source_text"]),prompt_identity=dp.sha("prompt"),source_language="ko",target_language="zh-TW",draft_text=text,quality_status="passed",semantic_status="passed",semantic_invariants=semantic or inv(),created_at=T0,status="verified")
def candidate(d,text,semantic=None):
    scope=dp.create_polish_scope(scope_type="full_chunk",original_draft_hash=d.draft_hash,selected_text=d.draft_text,surrounding_context=d.draft_text)
    return dp.create_polish_candidate(polish_id="polish-tic",draft=d,polish_text=text,polish_scope=scope,polish_reason="fixed regression",semantic_invariants=semantic or inv(),created_at=T0)

def test_tic_subject_historical_shift_fails_and_rolls_back():
    approved=fixture("B7-SUBJECT-APPROVED");bad=fixture("B7-SUBJECT-BAD");d=draft(approved["translation_text"]);p=candidate(d,bad["translation_text"],inv(subject="鄭泰義=理解者"));gate=dp.evaluate_tic_batch7_candidate(source_text=bad["source_text"],translation_text=bad["translation_text"],regression_id=bad["applicable_regression_ids"][0]);verification=dp.verify_polish_candidate(bad["source_text"],d,p,semantic_policy={"version":"v1"});decision=dp.decide_polish_rollback(d,p,verification);assert gate["status"]=="fail" and verification.status==dp.VerificationStatus.FAILED;assert decision.action==dp.RollbackAction.ROLLBACK_TO_DRAFT and decision.selected_hash==d.draft_hash
def test_tic_subject_approved_correction_passes_and_unrelated_does_not():
    approved=fixture("B7-SUBJECT-APPROVED");unrelated=fixture("B7-SUBJECT-UNRELATED");reg=approved["applicable_regression_ids"][0];assert dp.evaluate_tic_batch7_candidate(source_text=approved["source_text"],translation_text=approved["translation_text"],regression_id=reg)["status"]=="pass";assert dp.evaluate_tic_batch7_candidate(source_text=unrelated["source_text"],translation_text=unrelated["translation_text"],regression_id=reg)["status"]=="fail"
def test_tic_approved_lexical_choice_is_not_misclassified_as_semantic_mutation():
    approved=fixture("B7-LEXICAL-APPROVED");bad=fixture("B7-LEXICAL-BAD");reg=approved["applicable_regression_ids"][0];assert dp.evaluate_tic_batch7_candidate(source_text=approved["source_text"],translation_text=approved["translation_text"],regression_id=reg)["status"]=="pass";assert dp.evaluate_tic_batch7_candidate(source_text=bad["source_text"],translation_text=bad["translation_text"],regression_id=reg)["status"]=="fail"
    d=dp.create_draft_result(draft_id="d-lex",document_id="doc",chunk_index=1,source_hash=dp.sha(approved["source_text"]),prompt_identity=dp.sha("p"),source_language="ko",target_language="zh-TW",draft_text="理性的人",quality_status="passed",semantic_status="passed",semantic_invariants=inv(units=("human",)),created_at=T0,status="verified");p=candidate(d,approved["translation_text"],inv(units=("human",)));assert dp.verify_polish_candidate(approved["source_text"],d,p,semantic_policy={"version":"v1"}).status==dp.VerificationStatus.PASSED
def test_memory_and_scene_selection_fingerprints_control_polish_cache_only_when_selected():
    args=dict(draft_hash=dp.sha("draft"),polish_policy_version="p1",polish_scope_hash=dp.sha("scope"),semantic_policy_version="s1",character_memory_selection_fingerprint=dp.sha("char-selected"),context_scene_selection_fingerprint=dp.sha("scene-selected"),glossary_fingerprint=dp.sha("glossary"));base=dp.build_polish_cache_identity(**args);same=dp.build_polish_cache_identity(**args);changed=dp.build_polish_cache_identity(**{**args,"context_scene_selection_fingerprint":dp.sha("changed")});assert dp.compare_polish_cache_identity(base,same)["usable"];assert dp.compare_polish_cache_identity(base,changed)["reason"]=="memory_selection_changed"
def test_draft_polish_and_rollback_final_cache_identities_are_distinct():
    source=fixture("B7-SUBJECT-APPROVED")["source_text"];d=draft(fixture("B7-SUBJECT-APPROVED")["translation_text"]);polished=d.draft_text.replace("，他也會明白", "；他也會明白");p=candidate(d,polished,inv());verification=dp.verify_polish_candidate(source,d,p,semantic_policy={"version":"s1"});decision=dp.decide_polish_rollback(d,p,verification);di=dp.build_draft_cache_identity(source_hash=d.source_hash,prompt_identity=d.prompt_identity,draft_policy_version="d1",character_memory_selection_fingerprint=dp.sha("c"),context_scene_selection_fingerprint=dp.sha("s"),glossary_fingerprint=dp.sha("g"));pi=dp.build_polish_cache_identity(draft_hash=d.draft_hash,polish_policy_version="p1",polish_scope_hash=dp.sha("scope"),semantic_policy_version="s1",character_memory_selection_fingerprint=dp.sha("c"),context_scene_selection_fingerprint=dp.sha("s"),glossary_fingerprint=dp.sha("g"));final=dp.build_final_output_identity(rollback_decision=decision,draft_identity=di,polish_identity=pi,semantic_policy_version="s1",verification_status=verification.status);assert dp.draft_cache_key(di)!=dp.polish_cache_key(pi);assert final.selected_kind=="polish"
def test_cost_and_plan_are_offline_prepare_only():
    d=draft(fixture("B7-SUBJECT-APPROVED")["translation_text"]);scope=dp.create_polish_scope(scope_type="sentence_span",original_draft_hash=d.draft_hash,selected_text="句",surrounding_context=d.draft_text,start_identifier="s1",end_identifier="s1");trigger=dp.create_polish_trigger(trigger_id="t",trigger_type="translationese",evidence=({"rule":"fixture"},),confidence=.9,severity="nonblocking",scope=scope,estimated_quality_value=.8,estimated_cost=10);decision=dp.select_translation_mode(d,(trigger,),provider_policy={"health":"provider_healthy","rollback_available":True},cost_policy={"allow_second_request":True},timeout_policy={"timeout_risk":.1},quality_policy={});cost=dp.estimate_provider_cost(mode=decision.mode,draft_input_chars=100,draft_output_chars=100,polish_input_chars=20,polish_output_chars=20,provider_health="provider_healthy");plan=dp.build_dual_pass_execution_plan(decision,triggers=(trigger,),cost_estimate=cost,prepare_only=True);evidence=dp.create_execution_evidence(plan);assert plan.mode==dp.TranslationMode.SELECTIVE_POLISH and not plan.executed;assert not evidence.provider_executed and evidence.network_requests==0
def test_batch2_batch3_batch4_and_tic_files_match_head():
    prefixes=("core/character_memory_v2/","core/context_scene_memory/","core/chunk_cache_v2/","core/translation_intelligence_corpus/");files=subprocess.run(["git","-c","core.quotepath=false","ls-files"],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8").stdout.splitlines()
    for path in [x for x in files if x.startswith(prefixes)]:assert (ROOT/path).read_bytes()==subprocess.run(["git","show",f"HEAD:{path}"],cwd=ROOT,check=True,capture_output=True).stdout
def test_dual_pass_core_has_no_provider_runtime_prompt_or_network_dependency():
    forbidden={"requests","httpx","urllib","socket"};fragments=("ai_provider","production_runtime","prompt_builder","translation_pipeline")
    for path in (ROOT/"core/dual_pass_translation").glob("*.py"):
        tree=ast.parse(path.read_text(encoding="utf-8"));names=[]
        for node in ast.walk(tree):
            if isinstance(node,ast.Import):names.extend(x.name for x in node.names)
            elif isinstance(node,ast.ImportFrom):names.append(node.module or "")
        assert not forbidden&{x.split(".")[0] for x in names};assert not any(fragment in name for name in names for fragment in fragments)
def test_batch5_changes_stay_inside_allowlist():
    allowed=("core/dual_pass_translation/","tests/unit/test_dual_pass_translation.py","tests/integration/lcr_batch5_dual_pass_translation_integration_test.py","ntpe_lcr_batch5_dual_pass_prototype_test.py","audits/legacy_capability_recovery/batch5/","NTPE_LCR_BATCH5_AUDIT.zip");lines=subprocess.run(["git","status","--short"],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8").stdout.splitlines();assert all(line[3:].replace("\\","/").startswith(allowed) for line in lines)
