# =====================================================
# NTPE 1.2 Professional
# Stage-15.6 Quality Report / Export Layer
# =====================================================

from __future__ import annotations

import csv
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional

from .quality_context import QualityContext
from .quality_result import QualityIssue, QualityResult


STAGE = "Stage-15.6"
COMPONENT = "Quality Report / Export Layer"


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _safe_name(value: str | None, default: str = "quality_report") -> str:
    raw = (value or default).strip() or default
    allowed = []
    for ch in raw:
        if ch.isalnum() or ch in {"-", "_", "."}:
            allowed.append(ch)
        else:
            allowed.append("_")
    return "".join(allowed).strip("._") or default


@dataclass(frozen=True)
class QualityExportOptions:
    """Controls deterministic Stage-15.6 report output.

    The defaults intentionally create UTF-8 text files with stable field names,
    no secrets, and no transient runtime-only object representations.
    """

    include_source_preview: bool = False
    include_target_preview: bool = False
    preview_length: int = 160
    mask_metadata_secrets: bool = True
    indent: int = 2


@dataclass
class QualityExportBundle:
    """Paths generated by a QualityReportExporter run."""

    files: Dict[str, Path] = field(default_factory=dict)

    def add(self, key: str, path: Path) -> None:
        self.files[key] = path

    def to_dict(self) -> Dict[str, str]:
        return {key: str(path) for key, path in self.files.items()}


class SecretMasker:
    secret_keys = ("api_key", "apikey", "token", "secret", "password", "credential", "authorization")

    @classmethod
    def mask_mapping(cls, data: Mapping[str, Any]) -> Dict[str, Any]:
        masked: Dict[str, Any] = {}
        for key, value in data.items():
            if any(marker in key.lower() for marker in cls.secret_keys):
                masked[key] = cls.mask_value(value)
            elif isinstance(value, Mapping):
                masked[key] = cls.mask_mapping(value)
            elif isinstance(value, list):
                masked[key] = [cls.mask_mapping(v) if isinstance(v, Mapping) else v for v in value]
            else:
                masked[key] = value
        return masked

    @staticmethod
    def mask_value(value: Any) -> str:
        text = str(value or "")
        if not text:
            return ""
        if len(text) <= 8:
            return "***"
        return f"{text[:2]}***{text[-2:]}"


class QualityReportSerializer:
    """Serializes QualityContext + QualityResult to clean export payloads."""

    def __init__(self, options: QualityExportOptions | None = None) -> None:
        self.options = options or QualityExportOptions()

    def to_payload(self, context: QualityContext, result: QualityResult) -> Dict[str, Any]:
        metadata = dict(context.metadata or {})
        if self.options.mask_metadata_secrets:
            metadata = SecretMasker.mask_mapping(metadata)

        payload: Dict[str, Any] = {
            "stage": STAGE,
            "component": COMPONENT,
            "generated_at": _utc_now(),
            "context": {
                "segment_id": context.segment_id,
                "session_id": context.session_id,
                "provider_name": context.provider_name,
                "model_name": context.model_name,
                "language_pair": context.language_pair,
                "source_length": context.source_length,
                "translated_length": context.translated_length,
                "glossary_term_count": len(context.glossary or {}),
                "metadata": metadata,
            },
            "quality": result.to_dict(),
            "summary": self.to_summary(context, result),
        }
        if self.options.include_source_preview:
            payload["context"]["source_preview"] = (context.source_text or "")[: self.options.preview_length]
        if self.options.include_target_preview:
            payload["context"]["target_preview"] = (context.translated_text or "")[: self.options.preview_length]
        return payload

    def to_summary(self, context: QualityContext, result: QualityResult) -> Dict[str, Any]:
        severity_counts: Dict[str, int] = {}
        category_counts: Dict[str, int] = {}
        for issue in result.issues:
            severity_counts[issue.severity.value] = severity_counts.get(issue.severity.value, 0) + 1
            category_counts[issue.category] = category_counts.get(issue.category, 0) + 1
        return {
            "status": result.status.value,
            "score": round(float(result.score), 4),
            "issue_count": len(result.issues),
            "severity_counts": severity_counts,
            "category_counts": category_counts,
            "segment_id": context.segment_id,
            "session_id": context.session_id,
        }

    def to_text(self, context: QualityContext, result: QualityResult) -> str:
        summary = self.to_summary(context, result)
        lines = [
            "NTPE Quality Report",
            f"Stage: {STAGE}",
            f"Component: {COMPONENT}",
            f"Status: {summary['status']}",
            f"Score: {summary['score']}",
            f"Issues: {summary['issue_count']}",
            f"Segment: {context.segment_id or '-'}",
            f"Session: {context.session_id or '-'}",
            f"Provider: {context.provider_name or '-'}",
            f"Model: {context.model_name or '-'}",
            "",
            "Issues:",
        ]
        if not result.issues:
            lines.append("- None")
        for issue in result.issues:
            lines.append(f"- [{issue.severity.value}] {issue.category}/{issue.rule_name}: {issue.message}")
        return "\n".join(lines) + "\n"

    def issue_rows(self, result: QualityResult) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []
        for index, issue in enumerate(result.issues, start=1):
            rows.append(
                {
                    "index": index,
                    "severity": issue.severity.value,
                    "category": issue.category,
                    "rule_name": issue.rule_name,
                    "message": issue.message,
                    "score_penalty": issue.score_penalty,
                    "auto_repairable": issue.auto_repairable,
                    "metadata": json.dumps(issue.metadata, ensure_ascii=False, sort_keys=True),
                }
            )
        return rows


class QualityReportExporter:
    """Writes JSON, summary TXT, metrics JSON and issues CSV reports."""

    def __init__(self, output_dir: str | Path, options: QualityExportOptions | None = None) -> None:
        self.output_dir = Path(output_dir)
        self.options = options or QualityExportOptions()
        self.serializer = QualityReportSerializer(self.options)

    def export(
        self,
        context: QualityContext,
        result: QualityResult,
        *,
        basename: str | None = None,
        formats: Iterable[str] = ("json", "summary", "metrics", "issues_csv"),
    ) -> QualityExportBundle:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        name = _safe_name(basename or context.segment_id or context.session_id or "quality_report")
        requested = {fmt.lower() for fmt in formats}
        bundle = QualityExportBundle()
        payload = self.serializer.to_payload(context, result)

        if "json" in requested:
            path = self.output_dir / f"{name}.quality.json"
            path.write_text(json.dumps(payload, ensure_ascii=False, indent=self.options.indent), encoding="utf-8")
            bundle.add("json", path)

        if "summary" in requested or "txt" in requested:
            path = self.output_dir / f"{name}.quality.txt"
            path.write_text(self.serializer.to_text(context, result), encoding="utf-8")
            bundle.add("summary", path)

        if "metrics" in requested:
            path = self.output_dir / f"{name}.metrics.json"
            metrics = {
                "stage": STAGE,
                "component": COMPONENT,
                "generated_at": payload["generated_at"],
                "summary": payload["summary"],
                "metrics": result.metrics,
            }
            path.write_text(json.dumps(metrics, ensure_ascii=False, indent=self.options.indent), encoding="utf-8")
            bundle.add("metrics", path)

        if "issues_csv" in requested or "csv" in requested:
            path = self.output_dir / f"{name}.issues.csv"
            rows = self.serializer.issue_rows(result)
            fieldnames = ["index", "severity", "category", "rule_name", "message", "score_penalty", "auto_repairable", "metadata"]
            with path.open("w", encoding="utf-8-sig", newline="") as handle:
                writer = csv.DictWriter(handle, fieldnames=fieldnames)
                writer.writeheader()
                writer.writerows(rows)
            bundle.add("issues_csv", path)

        return bundle


__all__ = [
    "COMPONENT",
    "STAGE",
    "QualityExportBundle",
    "QualityExportOptions",
    "QualityReportExporter",
    "QualityReportSerializer",
    "SecretMasker",
]
