"""Stage 6.11 queue-admission authorization consumption errors."""

class QueueAdmissionAuthorizationConsumptionError(Exception): pass
class QueueAdmissionAuthorizationConsumptionPathError(QueueAdmissionAuthorizationConsumptionError): pass
class QueueAdmissionAuthorizationConsumptionSchemaError(QueueAdmissionAuthorizationConsumptionError): pass
class QueueAdmissionAuthorizationConsumptionIntegrityError(QueueAdmissionAuthorizationConsumptionError): pass
class QueueAdmissionAuthorizationAlreadyConsumedError(QueueAdmissionAuthorizationConsumptionError): pass
class QueueAdmissionAuthorizationConsumptionConflictError(QueueAdmissionAuthorizationConsumptionError): pass
class QueueAdmissionAuthorizationConsumptionCommitError(QueueAdmissionAuthorizationConsumptionError): pass
class QueueAdmissionAuthorizationConsumptionVerificationError(QueueAdmissionAuthorizationConsumptionError): pass
