# Write provider.py
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("from __future__ import annotations\n")
    f.write("from dataclasses import dataclass\n")
    f.write("from pathlib import Path\n")
    f.write("from typing import Any, Dict, List, Optional\n")
    f.write("from core.knowledge_compilation.package_builder import PackageReader, create_package_reader\n")
    f.write("from core.knowledge_compilation.models import CompilationPackage, CompilationManifest\n")
    f.write("from core.knowledge_compilation.checksum import ChecksumCalculator, DEFAULT_CALCULATOR\n")
    f.write("\n")
    f.write("@dataclass(frozen=True, slots=True)\n")
    f.write("class EntityQuery:\n")
    f.write("    entity_type: str\n")
    f.write("    entity_id = None\n")
    f.write("    name = None\n")
    f.write("    limit = None\n")
    f.write("    domain = None\n")
    f.write("\n")
    f.write("class KnowledgePackageProvider:\n")
    f.write("    ENTITY_TYPES = (\"character\", \"glossary\", \"scene\", \"narrative\", \"style\")\n")
    f.write("    def __init__(self, package_dir, verify_on_load=True, calculator=None):\n")
    f.write("        self._package_dir = Path(package_dir)\n")
    f.write("        self._calculator = calculator or DEFAULT_CALCULATOR\n")
    f.write("        self._reader = create_package_reader(self._package_dir)\n")
    f.write("        self._package = None\n")
    f.write("        self._manifest = None\n")
    f.write("        self._entity_cache = {}\n")
    f.write("        self._verified = False\n")
    f.write("        if verify_on_load:\n")
    f.write("            self.verify()\n")
    f.write("    @property\n")
    f.write("    def package_dir(self):\n")
    f.write("        return self._package_dir\n")
    f.write("    @property\n")
    f.write("    def package(self):\n")
    f.write("        if self._package is None:\n")
    f.write("            self._package = self._reader.package\n")
    f.write("        return self._package\n")
    f.write("    @property\n")
    f.write("    def manifest(self):\n")
    f.write("        if self._manifest is None:\n")
    f.write("            self._manifest = self._reader.manifest\n")
    f.write("        return self._manifest\n")

print("Done")