# Write provider.py - package metadata, verification, context, exports
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("    # === Package Metadata ===\n")
    f.write("\n")
    f.write("    def get_package_info(self):\n")
    f.write("        return {\n")
    f.write('            "package_id": self.manifest.package_id,\n')
    f.write('            "package_version": self.manifest.package_version,\n')
    f.write('            "schema_versions": dict(self.manifest.schema_versions),\n')
    f.write('            "entity_counts": dict(self.manifest.entity_counts),\n')
    f.write('            "created_at": self.manifest.created_at,\n')
    f.write('            "compiler_version": self.manifest.compiler_version,\n')
    f.write('            "checksum": self.package.checksum,\n')
    f.write("        }\n")
    f.write("\n")
    f.write("    def get_entity_types(self):\n")
    f.write("        return self.package.get_entity_types()\n")
    f.write("\n")
    f.write("    def get_entity_count(self, entity_type):\n")
    f.write("        return self.package.get_entity_count(entity_type)\n")
    f.write("\n")
    f.write("    def total_entity_count(self):\n")
    f.write("        return self.package.total_entity_count()\n")
    f.write("\n")
    f.write("    # === Verification ===\n")
    f.write("\n")
    f.write("    def verify(self):\n")
    f.write("        if not self.package.verify_checksum(self._calculator):\n")
    f.write('            raise ValueError(f"Checksum verification failed for package at {self._package_dir}")\n')
    f.write("        for entity_type, count in self.manifest.entity_counts.items():\n")
    f.write("            actual = self.package.get_entity_count(entity_type)\n")
    f.write("            if actual != count:\n")
    f.write("                raise ValueError(\n")
    f.write('                    f"Manifest entity count mismatch for {entity_type}: "\n')
    f.write('                    f"manifest={count}, actual={actual}"\n')
    f.write("                )\n")
    f.write("        for entity_type in self.ENTITY_TYPES:\n")
    f.write("            if entity_type in self.manifest.entity_counts:\n")
    f.write('                plural_map = {"glossary": "glossaries"}\n')
    f.write("                plural = plural_map.get(entity_type, f\"{entity_type}s\")\n")
    f.write("                file_path = self._package_dir / f\"{plural}.json\"\n")
    f.write("                if not file_path.exists():\n")
    f.write('                    raise ValueError(f"Required entity file missing: {file_path}")\n')
    f.write("        manifest_path = self._package_dir / \"manifest.json\"\n")
    f.write("        if not manifest_path.exists():\n")
    f.write('            raise ValueError(f"Manifest file missing: {manifest_path}")\n')
    f.write("        self._verified = True\n")
    f.write("        return True\n")
    f.write("\n")
    f.write("    def is_verified(self):\n")
    f.write("        return self._verified\n")
    f.write("\n")
    f.write("    # === Context Building (for Prompt Pipeline) ===\n")
    f.write("\n")
    f.write("    def build_context(self, entity_types=None):\n")
    f.write("        types = entity_types or self.get_entity_types()\n")
    f.write("        domains = {}\n")
    f.write("        items = []\n")
    f.write("        for entity_type in types:\n")
    f.write("            entities = self._get_entities(entity_type, None, None)\n")
    f.write("            for entity in entities:\n")
    f.write('                key = entity.get("entity_id", entity.get("name", ""))\n')
    f.write("                domains.setdefault(entity_type, {})[key] = entity\n")
    f.write("                items.append(entity)\n")
    f.write("        return {\n")
    f.write('            "type": "knowledge_context",\n')
    f.write('            "version": "rm-5.7.5",\n')
    f.write('            "items": items,\n')
    f.write('            "domains": domains,\n')
    f.write('            "manifest": self.manifest.to_dict(),\n')
    f.write("        }\n")
    f.write("\n")
    f.write("    def attach_to_prompt_package(self, prompt_package=None):\n")
    f.write("        next_package = dict(prompt_package or {})\n")
    f.write("        components = list(next_package.get(\"context_components\", []))\n")
    f.write("        components.append(self.build_context())\n")
    f.write("        next_package[\"context_components\"] = components\n")
    f.write("        return next_package\n")
    f.write("\n\n")
    f.write("def create_provider(package_dir, verify_on_load=True):\n")
    f.write("    return KnowledgePackageProvider(package_dir, verify_on_load=verify_on_load)\n")
    f.write("\n\n")
    f.write("__all__ = [\n")
    f.write('    "KnowledgePackageProvider",\n')
    f.write('    "EntityQuery",\n')
    f.write('    "create_provider",\n')
    f.write("]\n")

print("Done")