# Write provider.py - methods
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("    # === Typed Entity Access Methods (Runtime API) ===\n")
    f.write("\n")
    f.write("    def get_character(self, entity_id=None, name=None):\n")
    f.write('        return self._get_entities("character", entity_id, name)\n')
    f.write("\n")
    f.write("    def get_glossary(self, entity_id=None, name=None):\n")
    f.write('        return self._get_entities("glossary", entity_id, name)\n')
    f.write("\n")
    f.write("    def get_scene(self, entity_id=None, name=None):\n")
    f.write('        return self._get_entities("scene", entity_id, name)\n')
    f.write("\n")
    f.write("    def get_narrative(self, entity_id=None, name=None):\n")
    f.write('        return self._get_entities("narrative", entity_id, name)\n')
    f.write("\n")
    f.write("    def get_style(self, entity_id=None, name=None):\n")
    f.write('        return self._get_entities("style", entity_id, name)\n')
    f.write("\n")
    f.write("    def get_entities(self, entity_type, entity_id=None, name=None):\n")
    f.write("        if entity_type not in self.ENTITY_TYPES:\n")
    f.write('            raise ValueError(f"Unknown entity type: {entity_type}. Supported: {self.ENTITY_TYPES}")\n')
    f.write("        return self._get_entities(entity_type, entity_id, name)\n")
    f.write("\n")
    f.write("    # === Internal Methods ===\n")
    f.write("\n")
    f.write("    def _get_entities(self, entity_type, entity_id, name):\n")
    f.write("        if entity_type not in self._entity_cache:\n")
    f.write("            self._entity_cache[entity_type] = self._reader.get_entities(entity_type)\n")
    f.write("        entities = self._entity_cache[entity_type]\n")
    f.write("        if entity_id is not None:\n")
    f.write('            entities = [e for e in entities if e.get("entity_id") == entity_id]\n')
    f.write("        if name is not None:\n")
    f.write('            entities = [e for e in entities if e.get("name") == name]\n')
    f.write("        return entities\n")

print("Done")