# Update __init__.py to include legacy mapper
with open("D:/Python/NTPE/core/knowledge/compatibility/__init__.py", "w", encoding="utf-8") as f:
    f.write('"""')
    f.write('\n')
    f.write('RM-5.7.5 Knowledge Package Compatibility Layer.')
    f.write('\n')
    f.write('\n')
    f.write('This module provides the read-only interface for Translation Runtime')
    f.write('\n')
    f.write('to access Frozen Knowledge Packages.')
    f.write('\n')
    f.write('"""')
    f.write('\n')
    f.write('\n')
    f.write('from .provider import KnowledgePackageProvider, EntityQuery, create_provider')
    f.write('\n')
    f.write('from .legacy_mapper import LegacyMapper, LegacyMapping, create_legacy_mapper')
    f.write('\n')
    f.write('\n')
    f.write('__all__ = [')
    f.write('\n')
    f.write('    "KnowledgePackageProvider",')
    f.write('\n')
    f.write('    "EntityQuery",')
    f.write('\n')
    f.write('    "create_provider",')
    f.write('\n')
    f.write('    "LegacyMapper",')
    f.write('\n')
    f.write('    "LegacyMapping",')
    f.write('\n')
    f.write('    "create_legacy_mapper",')
    f.write('\n')
    f.write(']')
    f.write('\n')

print("Done")