# Write freeze_verifier.py - part 3c compatibility and readonly
with open("D:/Python/NTPE/core/knowledge/compatibility/freeze_verifier.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    def _check_compatibility(self, report: FreezeVerificationReport) -> None:')
    f.write('\n')
    f.write('        """Verify package is compatible with current provider schema."""')
    f.write('\n')
    f.write('        required_types = ("character", "glossary", "scene", "narrative", "style")')
    f.write('\n')
    f.write('        all_passed = True')
    f.write('\n')
    f.write('        details = []')
    f.write('\n')
    f.write('\n')
    f.write('        for entity_type in required_types:')
    f.write('\n')
    f.write('            count = self.package.get_entity_count(entity_type)')
    f.write('\n')
    f.write('            if count == 0:')
    f.write('\n')
    f.write('                details.append(f"{entity_type}: 0 entities (warning)")')
    f.write('\n')
    f.write('            else:')
    f.write('\n')
    f.write('                details.append(f"{entity_type}: {count} entities")')
    f.write('\n')
    f.write('\n')
    f.write('        required_manifest_fields = (')
    f.write('\n')
    f.write('            "package_id",')
    f.write('\n')
    f.write('            "package_version",')
    f.write('            "schema_versions",')
    f.write('            "entity_counts",')
    f.write('            "created_at",')
    f.write('            "compiler_version",')
    f.write('        )')
    f.write('\n')
    f.write('\n')
    f.write('        for field in required_manifest_fields:')
    f.write('\n')
    f.write('            if not hasattr(self.manifest, field):')
    f.write('\n')
    f.write('                all_passed = False')
    f.write('\n')
    f.write('                details.append(f"manifest missing {field}")')
    f.write('\n')
    f.write('\n')
    f.write('        report.add_result(VerificationResult(')
    f.write('\n')
    f.write('            check_name="compatibility",')
    f.write('\n')
    f.write('            passed=all_passed,')
    f.write('\n')
    f.write('            detail="; ".join(details),')
    f.write('\n')
    f.write('            severity="error" if not all_passed else "info",')
    f.write('\n')
    f.write('        ))')
    f.write('\n')
    f.write('\n')
    f.write('    def _check_readonly_boundary(self, report: FreezeVerificationReport) -> None:')
    f.write('\n')
    f.write('        """Verify runtime read-only boundary (no write methods exposed)."""')
    f.write('\n')
    f.write('        from core.knowledge.compatibility.provider import KnowledgePackageProvider')
    f.write('\n')
    f.write('\n')
    f.write('        provider = KnowledgePackageProvider(')
    f.write('\n')
    f.write('            self._package_dir,')
    f.write('\n')
    f.write('            verify_on_load=False,')
    f.write('\n')
    f.write('        )')
    f.write('\n')
    f.write('\n')
    f.write('        write_methods = [')
    f.write('\n')
    f.write('            "write", "save", "delete", "update",')
    f.write('\n')
    f.write('            "create", "build", "compile", "extract",')
    f.write('\n')
    f.write('            "validate", "review",')
    f.write('\n')
    f.write('        ]')
    f.write('\n')
    f.write('\n')
    f.write('        found_write = []')
    f.write('\n')
    f.write('        for method in write_methods:')
    f.write('\n')
    f.write('            if hasattr(provider, method):')
    f.write('\n')
    f.write('                found_write.append(method)')
    f.write('\n')
    f.write('\n')
    f.write('        passed = len(found_write) == 0')
    f.write('\n')
    f.write('        detail = "No write methods found" if passed else f"Write methods found: {found_write}"')
    f.write('\n')
    f.write('\n')
    f.write('        report.add_result(VerificationResult(')
    f.write('\n')
    f.write('            check_name="readonly_boundary",')
    f.write('\n')
    f.write('            passed=passed,')
    f.write('\n')
    f.write('            detail=detail,')
    f.write('\n')
    f.write('            severity="error",')
    f.write('\n')
    f.write('        ))')
    f.write('\n')

print("Part 3c done")