# Write legacy_mapper.py - part 2 class
with open("D:/Python/NTPE/core/knowledge/compatibility/legacy_mapper.py", "a", encoding="utf-8") as f:
    f.write('\n\n')
    f.write('class LegacyMapper:')
    f.write('\n')
    f.write('    """Maps legacy knowledge sources to Frozen Knowledge Package v2."""')
    f.write('\n')
    f.write('\n')
    f.write('    # Legacy to v2 entity type mapping')
    f.write('\n')
    f.write('    LEGACY_ENTITY_MAP = {')
    f.write('\n')
    f.write('        "character_memory.json": "character",')
    f.write('\n')
    f.write('        "glossary.json": "glossary",')
    f.write('\n')
    f.write('        "knowledge_base.json": "character",  # contains characters + glossary')
    f.write('\n')
    f.write('        "character_match_dictionary.json": "character",')
    f.write('\n')
    f.write('        "character_alias_index.json": "character",')
    f.write('\n')
    f.write('    }')
    f.write('\n')
    f.write('\n')
    f.write('    # V2 package file names (with irregular plurals)')
    f.write('\n')
    f.write('    V2_FILE_MAP = {')
    f.write('\n')
    f.write('        "character": "characters.json",')
    f.write('\n')
    f.write('        "glossary": "glossaries.json",')
    f.write('\n')
    f.write('        "scene": "scenes.json",')
    f.write('\n')
    f.write('        "narrative": "narrative.json",')
    f.write('\n')
    f.write('        "style": "style.json",')
    f.write('\n')
    f.write('    }')
    f.write('\n')
    f.write('\n')
    f.write('    def __init__(self, v2_package_root: str | Path = "artifacts/knowledge_packages/v1"):')
    f.write('\n')
    f.write('        self._v2_root = Path(v2_package_root)')
    f.write('\n')
    f.write('\n')
    f.write('    def get_legacy_mappings(self) -> List[LegacyMapping]:')
    f.write('\n')
    f.write('        """Get all legacy to v2 mappings."""')
    f.write('\n')
    f.write('        mappings = []')
    f.write('\n')
    f.write('        for legacy_name, entity_type in self.LEGACY_ENTITY_MAP.items():')
    f.write('\n')
    f.write('            v2_file = self.V2_FILE_MAP.get(entity_type, f"{entity_type}s.json")')
    f.write('\n')
    f.write('            v2_path = self._v2_root / v2_file')
    f.write('\n')
    f.write('            mappings.append(LegacyMapping(')
    f.write('\n')
    f.write('                legacy_path=f"memory/{legacy_name}",')
    f.write('\n')
    f.write('                entity_type=entity_type,')
    f.write('\n')
    f.write('                v2_package_path=str(v2_path),')
    f.write('\n')
    f.write('                description=f"Legacy {legacy_name} mapped to v2 {entity_type} package"')
    f.write('\n')
    f.write('            ))')
    f.write('\n')
    f.write('\n')
    f.write('        # Add glossary.txt as special case')
    f.write('\n')
    f.write('        mappings.append(LegacyMapping(')
    f.write('\n')
    f.write('            legacy_path="data/glossary.txt",')
    f.write('\n')
    f.write('            entity_type="glossary",')
    f.write('\n')
    f.write('            v2_package_path=str(self._v2_root / "glossaries.json"),')
    f.write('\n')
    f.write('            description="Legacy flat glossary.txt mapped to v2 structured glossary package"')
    f.write('\n')
    f.write('        ))')
    f.write('\n')
    f.write('\n')
    f.write('        return mappings')
    f.write('\n')

print("Part 2 done")