# Write freeze_verifier.py - part 2 dataclasses and class
with open("D:/Python/NTPE/core/knowledge/compatibility/freeze_verifier.py", "a", encoding="utf-8") as f:
    f.write('\n\n')
    f.write('@dataclass(frozen=True, slots=True)')
    f.write('\n')
    f.write('class VerificationResult:')
    f.write('\n')
    f.write('    """Result of a single verification check."""')
    f.write('\n')
    f.write('    check_name: str')
    f.write('\n')
    f.write('    passed: bool')
    f.write('\n')
    f.write('    detail: str = ""')
    f.write('\n')
    f.write('    severity: str = "error"  # "error" | "warning" | "info"')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('@dataclass(frozen=True, slots=True)')
    f.write('\n')
    f.write('class FreezeVerificationReport:')
    f.write('\n')
    f.write('    """Complete freeze verification report."""')
    f.write('\n')
    f.write('    package_dir: str')
    f.write('\n')
    f.write('    results: List[VerificationResult] = field(default_factory=list)')
    f.write('\n')
    f.write('    overall_passed: bool = False')
    f.write('\n')
    f.write('\n')
    f.write('    def add_result(self, result: VerificationResult) -> None:')
    f.write('\n')
    f.write('        object.__setattr__(self, "results", self.results + [result])')
    f.write('\n')
    f.write('\n')
    f.write('    def get_failed(self) -> List[VerificationResult]:')
    f.write('\n')
    f.write('        return [r for r in self.results if not r.passed and r.severity == "error"]')
    f.write('\n')
    f.write('\n')
    f.write('    def get_warnings(self) -> List[VerificationResult]:')
    f.write('\n')
    f.write('        return [r for r in self.results if not r.passed and r.severity == "warning"]')
    f.write('\n')
    f.write('\n')
    f.write('    def finalize(self) -> None:')
    f.write('\n')
    f.write('        object.__setattr__(self, "overall_passed", len(self.get_failed()) == 0)')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('class FreezeVerifier:')
    f.write('\n')
    f.write('    """Complete freeze verification for Frozen Knowledge Packages."""')
    f.write('\n')
    f.write('\n')
    f.write('    def __init__(')
    f.write('\n')
    f.write('        self,')
    f.write('\n')
    f.write('        package_dir: str | Path,')
    f.write('\n')
    f.write('        calculator: ChecksumCalculator | None = None,')
    f.write('\n')
    f.write('        source_dir: str | Path | None = None,  # For deterministic rebuild check')
    f.write('\n')
    f.write('    ) -> None:')
    f.write('\n')
    f.write('        self._package_dir = Path(package_dir)')
    f.write('\n')
    f.write('        self._calculator = calculator or DEFAULT_CALCULATOR')
    f.write('\n')
    f.write('        self._reader = create_package_reader(self._package_dir)')
    f.write('\n')
    f.write('        self._source_dir = Path(source_dir) if source_dir else None')
    f.write('\n')
    f.write('\n')
    f.write('    @property')
    f.write('\n')
    f.write('    def package_dir(self) -> Path:')
    f.write('\n')
    f.write('        return self._package_dir')
    f.write('\n')
    f.write('\n')
    f.write('    @property')
    f.write('\n')
    f.write('    def package(self) -> CompilationPackage:')
    f.write('\n')
    f.write('        return self._reader.package')
    f.write('\n')
    f.write('\n')
    f.write('    @property')
    f.write('\n')
    f.write('    def manifest(self) -> CompilationManifest:')
    f.write('\n')
    f.write('        return self._reader.manifest')
    f.write('\n')

print("Part 2 done")