# Write freeze_verifier.py - part 3b deterministic rebuild
with open("D:/Python/NTPE/core/knowledge/compatibility/freeze_verifier.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    def _check_deterministic_rebuild(self, report: FreezeVerificationReport) -> None:')
    f.write('\n')
    f.write('        """Verify package can be deterministically rebuilt from source."""')
    f.write('\n')
    f.write('        if not self._source_dir:')
    f.write('\n')
    f.write('            report.add_result(VerificationResult(')
    f.write('\n')
    f.write('                check_name="deterministic_rebuild",')
    f.write('\n')
    f.write('                passed=True,')
    f.write('\n')
    f.write('                detail="Skipped (no source_dir provided)",')
    f.write('\n')
    f.write('                severity="info",')
    f.write('\n')
    f.write('            ))')
    f.write('\n')
    f.write('            return')
    f.write('\n')
    f.write('\n')
    f.write('        try:')
    f.write('\n')
    f.write('            config = CompilationConfig(')
    f.write('\n')
    f.write('                output_root=str(self._package_dir.parent),')
    f.write('\n')
    f.write('                version_dir=self._package_dir.name,')
    f.write('\n')
    f.write('                strict_mode=True,')
    f.write('\n')
    f.write('            )')
    f.write('\n')
    f.write('            compiler = KnowledgeCompiler(config)')
    f.write('\n')
    f.write('            rebuilt_package = compiler.compile(')
    f.write('\n')
    f.write('                entities=dict(self.package.entities),')
    f.write('\n')
    f.write('            )')
    f.write('\n')
    f.write('\n')
    f.write('            original_checksum = self.package.checksum')
    f.write('\n')
    f.write('            rebuilt_checksum = rebuilt_package.checksum')
    f.write('\n')
    f.write('\n')
    f.write('            passed = original_checksum == rebuilt_checksum')
    f.write('\n')
    f.write('            report.add_result(VerificationResult(')
    f.write('\n')
    f.write('                check_name="deterministic_rebuild",')
    f.write('\n')
    f.write('                passed=passed,')
    f.write('\n')
    f.write('                detail="Rebuild matches original" if passed else "Rebuild differs from original",')
    f.write('\n')
    f.write('                severity="error",')
    f.write('\n')
    f.write('            ))')
    f.write('\n')
    f.write('\n')
    f.write('        except Exception as e:')
    f.write('\n')
    f.write('            report.add_result(VerificationResult(')
    f.write('\n')
    f.write('                check_name="deterministic_rebuild",')
    f.write('\n')
    f.write('                passed=False,')
    f.write('\n')
    f.write('                detail=f"Rebuild failed: {e}",')
    f.write('\n')
    f.write('                severity="error",')
    f.write('\n')
    f.write('            ))')
    f.write('\n')

print("Part 3b done")