# Write freeze_verifier.py - part 4 main verify and exports
with open("D:/Python/NTPE/core/knowledge/compatibility/freeze_verifier.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    # === Main Verification Method ===')
    f.write('\n')
    f.write('\n')
    f.write('    def verify_all(self) -> FreezeVerificationReport:')
    f.write('\n')
    f.write('        """Run all verification checks and return complete report."""')
    f.write('\n')
    f.write('        report = FreezeVerificationReport(package_dir=str(self._package_dir))')
    f.write('\n')
    f.write('\n')
    f.write('        self._check_checksum(report)')
    f.write('\n')
    f.write('        self._check_manifest(report)')
    f.write('\n')
    f.write('        self._check_structure(report)')
    f.write('\n')
    f.write('        self._check_deterministic_rebuild(report)')
    f.write('\n')
    f.write('        self._check_compatibility(report)')
    f.write('\n')
    f.write('        self._check_readonly_boundary(report)')
    f.write('\n')
    f.write('\n')
    f.write('        report.finalize()')
    f.write('\n')
    f.write('        return report')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('def verify_package(')
    f.write('\n')
    f.write('    package_dir: str | Path,')
    f.write('\n')
    f.write('    calculator: ChecksumCalculator | None = None,')
    f.write('\n')
    f.write('    source_dir: str | Path | None = None,')
    f.write('\n')
    f.write(') -> FreezeVerificationReport:')
    f.write('\n')
    f.write('    """Convenience function to run full freeze verification."""')
    f.write('\n')
    f.write('    verifier = FreezeVerifier(package_dir, calculator, source_dir)')
    f.write('\n')
    f.write('    return verifier.verify_all()')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('__all__ = [')
    f.write('\n')
    f.write('    "FreezeVerifier",')
    f.write('\n')
    f.write('    "VerificationResult",')
    f.write('\n')
    f.write('    "FreezeVerificationReport",')
    f.write('\n')
    f.write('    "verify_package",')
    f.write('\n')
    f.write(']')
    f.write('\n')

print("Part 4 done")