# Write provider.py - part 5 package metadata
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("    # === Package Metadata ===\n")
    f.write("\n")
    f.write("    def get_package_info(self) -> Dict[str, Any]:\n")
    f.write('        """Get package metadata without loading full entities."""\n')
    f.write("        return {\n")
    f.write('            "package_id": self.manifest.package_id,\n')
    f.write('            "package_version": self.manifest.package_version,\n')
    f.write('            "schema_versions": dict(self.manifest.schema_versions),\n')
    f.write('            "entity_counts": dict(self.manifest.entity_counts),\n')
    f.write('            "created_at": self.manifest.created_at,\n')
    f.write('            "compiler_version": self.manifest.compiler_version,\n')
    f.write('            "checksum": self.package.checksum,\n')
    f.write("        }\n")
    f.write("\n")
    f.write("    def get_entity_types(self) -> List[str]:\n")
    f.write('        """Return list of entity types present in the package."""\n')
    f.write("        return self.package.get_entity_types()\n")
    f.write("\n")
    f.write("    def get_entity_count(self, entity_type: str) -> int:\n")
    f.write('        """Get count of entities for a specific type."""\n')
    f.write("        return self.package.get_entity_count(entity_type)\n")
    f.write("\n")
    f.write("    def total_entity_count(self) -> int:\n")
    f.write('        """Get total entity count across all types."""\n')
    f.write("        return self.package.total_entity_count()\n")

print("Part 5 done")