# Write legacy_mapper.py - part 3 methods and exports
with open("D:/Python/NTPE/core/knowledge/compatibility/legacy_mapper.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    def get_v2_path(self, entity_type: str) -> Path:')
    f.write('\n')
    f.write('        """Get the v2 package file path for an entity type."""')
    f.write('\n')
    f.write('        v2_file = self.V2_FILE_MAP.get(entity_type, f"{entity_type}s.json")')
    f.write('\n')
    f.write('        return self._v2_root / v2_file')
    f.write('\n')
    f.write('\n')
    f.write('    def get_legacy_path(self, entity_type: str) -> Optional[str]:')
    f.write('\n')
    f.write('        """Get the legacy path for an entity type (reverse lookup)."""')
    f.write('\n')
    f.write('        for legacy, etype in self.LEGACY_ENTITY_MAP.items():')
    f.write('\n')
    f.write('            if etype == entity_type:')
    f.write('\n')
    f.write('                return f"memory/{legacy}"')
    f.write('\n')
    f.write('        return None')
    f.write('\n')
    f.write('\n')
    f.write('    def list_legacy_paths(self) -> List[str]:')
    f.write('\n')
    f.write('        """List all known legacy paths."""')
    f.write('\n')
    f.write('        paths = [f"memory/{name}" for name in self.LEGACY_ENTITY_MAP.keys()]')
    f.write('\n')
    f.write('        paths.append("data/glossary.txt")')
    f.write('\n')
    f.write('        return paths')
    f.write('\n')
    f.write('\n')
    f.write('    def list_v2_paths(self) -> List[str]:')
    f.write('\n')
    f.write('        """List all v2 package file paths."""')
    f.write('\n')
    f.write('        return [str(self._v2_root / f) for f in self.V2_FILE_MAP.values()]')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('def create_legacy_mapper(v2_package_root: str | Path = "artifacts/knowledge_packages/v1") -> LegacyMapper:')
    f.write('\n')
    f.write('    """Convenience function to create a LegacyMapper."""')
    f.write('\n')
    f.write('    return LegacyMapper(v2_package_root)')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('__all__ = [')
    f.write('\n')
    f.write('    "LegacyMapper",')
    f.write('\n')
    f.write('    "LegacyMapping",')
    f.write('\n')
    f.write('    "create_legacy_mapper",')
    f.write('\n')
    f.write(']')
    f.write('\n')

print("Part 3 done")