# Write freeze_verifier.py - part 3a checksum and manifest
with open("D:/Python/NTPE/core/knowledge/compatibility/freeze_verifier.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    # === Individual Verification Checks ===')
    f.write('\n')
    f.write('\n')
    f.write('    def _check_checksum(self, report: FreezeVerificationReport) -> None:')
    f.write('\n')
    f.write('        """Verify package checksum matches manifest."""')
    f.write('\n')
    f.write('        passed = self.package.verify_checksum(self._calculator)')
    f.write('\n')
    f.write('        report.add_result(VerificationResult(')
    f.write('\n')
    f.write('            check_name="checksum",')
    f.write('\n')
    f.write('            passed=passed,')
    f.write('\n')
    f.write('            detail="Checksum matches" if passed else "Checksum mismatch",')
    f.write('\n')
    f.write('            severity="error",')
    f.write('\n')
    f.write('        ))')
    f.write('\n')
    f.write('\n')
    f.write('    def _check_manifest(self, report: FreezeVerificationReport) -> None:')
    f.write('\n')
    f.write('        """Verify manifest entity counts match actual entities."""')
    f.write('\n')
    f.write('        all_passed = True')
    f.write('\n')
    f.write('        details = []')
    f.write('\n')
    f.write('        for entity_type, count in self.manifest.entity_counts.items():')
    f.write('\n')
    f.write('            actual = self.package.get_entity_count(entity_type)')
    f.write('\n')
    f.write('            if actual != count:')
    f.write('\n')
    f.write('                all_passed = False')
    f.write('\n')
    f.write('                details.append(f"{entity_type}: manifest={count}, actual={actual}")')
    f.write('\n')
    f.write('            else:')
    f.write('\n')
    f.write('                details.append(f"{entity_type}: {count} OK")')
    f.write('\n')
    f.write('\n')
    f.write('        report.add_result(VerificationResult(')
    f.write('\n')
    f.write('            check_name="manifest",')
    f.write('\n')
    f.write('            passed=all_passed,')
    f.write('\n')
    f.write('            detail="; ".join(details),')
    f.write('\n')
    f.write('            severity="error",')
    f.write('\n')
    f.write('        ))')
    f.write('\n')
    f.write('\n')
    f.write('    def _check_structure(self, report: FreezeVerificationReport) -> None:')
    f.write('\n')
    f.write('        """Verify all required package files exist."""')
    f.write('\n')
    f.write('        all_passed = True')
    f.write('\n')
    f.write('        details = []')
    f.write('\n')
    f.write('        plural_map = {"glossary": "glossaries"}')
    f.write('\n')
    f.write('\n')
    f.write('        for entity_type in self.manifest.entity_counts.keys():')
    f.write('\n')
    f.write('            plural = plural_map.get(entity_type, f"{entity_type}s")')
    f.write('\n')
    f.write('            file_path = self._package_dir / f"{plural}.json"')
    f.write('\n')
    f.write('            if file_path.exists():')
    f.write('\n')
    f.write('                details.append(f"{plural}.json: exists")')
    f.write('\n')
    f.write('            else:')
    f.write('\n')
    f.write('                all_passed = False')
    f.write('\n')
    f.write('                details.append(f"{plural}.json: MISSING")')
    f.write('\n')
    f.write('\n')
    f.write('        manifest_path = self._package_dir / "manifest.json"')
    f.write('\n')
    f.write('        if manifest_path.exists():')
    f.write('\n')
    f.write('            details.append("manifest.json: exists")')
    f.write('\n')
    f.write('        else:')
    f.write('\n')
    f.write('            all_passed = False')
    f.write('\n')
    f.write('            details.append("manifest.json: MISSING")')
    f.write('\n')
    f.write('\n')
    f.write('        package_path = self._package_dir / "package.json"')
    f.write('\n')
    f.write('        if package_path.exists():')
    f.write('\n')
    f.write('            details.append("package.json: exists")')
    f.write('\n')
    f.write('        else:')
    f.write('\n')
    f.write('            all_passed = False')
    f.write('\n')
    f.write('            details.append("package.json: MISSING")')
    f.write('\n')
    f.write('\n')
    f.write('        report.add_result(VerificationResult(')
    f.write('\n')
    f.write('            check_name="structure",')
    f.write('\n')
    f.write('            passed=all_passed,')
    f.write('\n')
    f.write('            detail="; ".join(details),')
    f.write('\n')
    f.write('            severity="error",')
    f.write('\n')
    f.write('        ))')
    f.write('\n')

print("Part 3a done")