# Write final provider.py - part 1
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "w", encoding="utf-8") as f:
    f.write('"""')
    f.write('\n')
    f.write('RM-5.7.5 Knowledge Package Provider.')
    f.write('\n')
    f.write('\n')
    f.write('READ-ONLY provider for Translation Runtime.')
    f.write('\n')
    f.write('This is the ONLY interface Runtime may use to access Knowledge Packages.')
    f.write('\n')
    f.write('\n')
    f.write('PROHIBITED for Runtime:')
    f.write('\n')
    f.write('- Extractor (core.knowledge_generation)')
    f.write('\n')
    f.write('- Compiler (core.knowledge_compilation)')
    f.write('\n')
    f.write('- Review Engine (core.knowledge_review)')
    f.write('\n')
    f.write('- Validator (core.knowledge_validation)')
    f.write('\n')
    f.write('- Any generation pipeline component')
    f.write('\n')
    f.write('"""')
    f.write('\n')
    f.write('\n')
    f.write('from __future__ import annotations')
    f.write('\n')
    f.write('\n')
    f.write('from dataclasses import dataclass')
    f.write('\n')
    f.write('from pathlib import Path')
    f.write('\n')
    f.write('from typing import Any, Dict, List, Optional')
    f.write('\n')
    f.write('\n')
    f.write('from core.knowledge_compilation.package_builder import PackageReader, create_package_reader')
    f.write('\n')
    f.write('from core.knowledge_compilation.models import CompilationPackage, CompilationManifest')
    f.write('\n')
    f.write('from core.knowledge_compilation.checksum import ChecksumCalculator, DEFAULT_CALCULATOR')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('@dataclass(frozen=True, slots=True)')
    f.write('\n')
    f.write('class EntityQuery:')
    f.write('\n')
    f.write('    """Query parameters for entity retrieval."""')
    f.write('\n')
    f.write('    entity_type: str')
    f.write('\n')
    f.write('    entity_id: Optional[str] = None')
    f.write('\n')
    f.write('    name: Optional[str] = None')
    f.write('\n')
    f.write('    limit: Optional[int] = None')
    f.write('\n')
    f.write('    domain: Optional[str] = None')
    f.write('\n')
    f.write('\n')

print("Part 1 done")