# Write provider.py - part 3 properties and getters
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("    @property\n")
    f.write("    def package_dir(self) -> Path:\n")
    f.write('        """Return the package directory path."""\n')
    f.write("        return self._package_dir\n")
    f.write("\n")
    f.write("    @property\n")
    f.write("    def package(self) -> CompilationPackage:\n")
    f.write('        """Lazy-load the full compilation package."""\n')
    f.write("        if self._package is None:\n")
    f.write("            self._package = self._reader.package\n")
    f.write("        return self._package\n")
    f.write("\n")
    f.write("    @property\n")
    f.write("    def manifest(self) -> CompilationManifest:\n")
    f.write('        """Lazy-load the manifest."""\n')
    f.write("        if self._manifest is None:\n")
    f.write("            self._manifest = self._reader.manifest\n")
    f.write("        return self._manifest\n")
    f.write("\n")
    f.write("    # === Typed Entity Access Methods (Runtime API) ===\n")
    f.write("\n")
    f.write('    def get_character(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:\n')
    f.write('        """Get character entities. Filter by entity_id or name if provided."""\n')
    f.write('        return self._get_entities("character", entity_id, name)\n')
    f.write("\n")
    f.write('    def get_glossary(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:\n')
    f.write('        """Get glossary entities. Filter by entity_id or name if provided."""\n')
    f.write('        return self._get_entities("glossary", entity_id, name)\n')
    f.write("\n")
    f.write('    def get_scene(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:\n')
    f.write('        """Get scene entities. Filter by entity_id or name if provided."""\n')
    f.write('        return self._get_entities("scene", entity_id, name)\n')
    f.write("\n")
    f.write('    def get_narrative(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:\n')
    f.write('        """Get narrative entities. Filter by entity_id or name if provided."""\n')
    f.write('        return self._get_entities("narrative", entity_id, name)\n')
    f.write("\n")
    f.write('    def get_style(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:\n')
    f.write('        """Get style entities. Filter by entity_id or name if provided."""\n')
    f.write('        return self._get_entities("style", entity_id, name)\n')
    f.write("\n")
    f.write("    def get_entities(self, entity_type: str, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:\n")
    f.write('        """\n')
    f.write("        Generic entity retrieval.\n")
    f.write("\n")
    f.write("        Args:\n")
    f.write('            entity_type: One of "character", "glossary", "scene", "narrative", "style"\n')
    f.write("            entity_id: Optional entity ID filter\n")
    f.write("            name: Optional name filter\n")
    f.write("\n")
    f.write("        Returns:\n")
    f.write("            List of matching entities\n")
    f.write('        """\n')
    f.write("        if entity_type not in self.ENTITY_TYPES:\n")
    f.write('            raise ValueError(f"Unknown entity type: {entity_type}. Supported: {self.ENTITY_TYPES}")\n')
    f.write("        return self._get_entities(entity_type, entity_id, name)\n")

print("Part 3 done")