# Write RM_5_7_5_LEGACY_DEPRECATION_REPORT.md - part 1
with open("D:/Python/NTPE/docs/governance/rm5/RM_5_7_5_LEGACY_DEPRECATION_REPORT.md", "w", encoding="utf-8") as f:
    f.write('# RM-5.7.5 Legacy Deprecation Report')
    f.write('\n')
    f.write('\n')
    f.write('**Date**: 2026-08-03  ')
    f.write('\n')
    f.write('**Status**: Complete  ')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## Overview')
    f.write('\n')
    f.write('\n')
    f.write('This report documents the migration from legacy knowledge storage (v1) to')
    f.write('\n')
    f.write('Frozen Knowledge Packages (v2) as part of RM-5.7.5 Integration & Legacy Migration.')
    f.write('\n')
    f.write('\n')
    f.write('The legacy system used scattered JSON files in `memory/` and flat text files in `data/`.')
    f.write('\n')
    f.write('The v2 system consolidates all knowledge into a single, versioned, verified package')
    f.write('\n')
    f.write('at `artifacts/knowledge_packages/v1/` with deterministic builds and read-only runtime access.')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## Legacy Sources (v1)')
    f.write('\n')
    f.write('\n')
    f.write('| Legacy Path | Type | Description | Status |')
    f.write('\n')
    f.write('|-------------|------|-------------|--------|')
    f.write('\n')
    f.write('| `memory/character_memory.json` | Character | Extracted character database | **Deprecated** |')
    f.write('\n')
    f.write('| `memory/glossary.json` | Glossary | Structured glossary database | **Deprecated** |')
    f.write('\n')
    f.write('| `memory/knowledge_base.json` | Composite | Merged character + glossary | **Deprecated** |')
    f.write('\n')
    f.write('| `memory/character_match_dictionary.json` | Character | Alias resolution index | **Deprecated** |')
    f.write('\n')
    f.write('| `memory/character_alias_index.json` | Character | Resolver-compatible aliases | **Deprecated** |')
    f.write('\n')
    f.write('| `data/glossary.txt` | Glossary | Flat key=value glossary | **Deprecated** |')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## v2 Package Structure')
    f.write('\n')
    f.write('\n')
    f.write('```')
    f.write('\n')
    f.write('artifacts/knowledge_packages/v1/')
    f.write('\n')
    f.write('|-- characters.json      # Character entities')
    f.write('\n')
    f.write('|-- glossaries.json      # Glossary entities (irregular plural)')
    f.write('\n')
    f.write('|-- scenes.json          # Scene entities')
    f.write('\n')
    f.write('|-- narrative.json       # Narrative entities')
    f.write('\n')
    f.write('|-- style.json           # Style entities')
    f.write('\n')
    f.write('|-- manifest.json        # Package manifest with counts, versions, checksum')
    f.write('\n')
    f.write('|-- package.json         # Full package (all entities + manifest)')
    f.write('\n')
    f.write('```')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')

print("Part 1 done")