# Write provider.py - part 4a metadata
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    # === Package Metadata ===')
    f.write('\n')
    f.write('\n')
    f.write('    def get_package_info(self) -> Dict[str, Any]:')
    f.write('\n')
    f.write('        """Get package metadata without loading full entities."""')
    f.write('\n')
    f.write('        return {')
    f.write('\n')
    f.write('            "package_id": self.manifest.package_id,')
    f.write('\n')
    f.write('            "package_version": self.manifest.package_version,')
    f.write('\n')
    f.write('            "schema_versions": dict(self.manifest.schema_versions),')
    f.write('\n')
    f.write('            "entity_counts": dict(self.manifest.entity_counts),')
    f.write('\n')
    f.write('            "created_at": self.manifest.created_at,')
    f.write('\n')
    f.write('            "compiler_version": self.manifest.compiler_version,')
    f.write('\n')
    f.write('            "checksum": self.package.checksum,')
    f.write('\n')
    f.write('        }')
    f.write('\n')
    f.write('\n')
    f.write('    def get_entity_types(self) -> List[str]:')
    f.write('\n')
    f.write('        """Return list of entity types present in the package."""')
    f.write('\n')
    f.write('        return self.package.get_entity_types()')
    f.write('\n')
    f.write('\n')
    f.write('    def get_entity_count(self, entity_type: str) -> int:')
    f.write('\n')
    f.write('        """Get count of entities for a specific type."""')
    f.write('\n')
    f.write('        return self.package.get_entity_count(entity_type)')
    f.write('\n')
    f.write('\n')
    f.write('    def total_entity_count(self) -> int:')
    f.write('\n')
    f.write('        """Get total entity count across all types."""')
    f.write('\n')
    f.write('        return self.package.total_entity_count()')
    f.write('\n')
    f.write('\n')
    f.write('    # === Verification ===')
    f.write('\n')
    f.write('\n')
    f.write('    def verify(self) -> bool:')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        Verify package integrity (checksum, manifest, structure).')
    f.write('\n')
    f.write('\n')
    f.write('        Returns:')
    f.write('\n')
    f.write('            True if package is valid')
    f.write('\n')
    f.write('\n')
    f.write('        Raises:')
    f.write('\n')
    f.write('            ValueError: If verification fails')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        # Verify checksum')
    f.write('\n')
    f.write('        if not self.package.verify_checksum(self._calculator):')
    f.write('\n')
    f.write('            raise ValueError(f"Checksum verification failed for package at {self._package_dir}")')
    f.write('\n')

print("Part 4a done")