# Write provider.py - part 6 verification
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("    # === Verification ===\n")
    f.write("\n")
    f.write("    def verify(self) -> bool:\n")
    f.write('        """\n')
    f.write("        Verify package integrity (checksum, manifest, structure).\n")
    f.write("\n")
    f.write("        Returns:\n")
    f.write("            True if package is valid\n")
    f.write("\n")
    f.write("        Raises:\n")
    f.write("            ValueError: If verification fails\n")
    f.write('        """\n')
    f.write("        # Verify checksum\n")
    f.write("        if not self.package.verify_checksum(self._calculator):\n")
    f.write('            raise ValueError(f"Checksum verification failed for package at {self._package_dir}")\n')
    f.write("\n")
    f.write("        # Verify manifest matches entities\n")
    f.write("        for entity_type, count in self.manifest.entity_counts.items():\n")
    f.write("            actual = self.package.get_entity_count(entity_type)\n")
    f.write("            if actual != count:\n")
    f.write("                raise ValueError(\n")
    f.write('                    f"Manifest entity count mismatch for {entity_type}: "\n')
    f.write('                    f"manifest={count}, actual={actual}"\n')
    f.write("                )\n")
    f.write("\n")
    f.write("        # Verify all required files exist\n")
    f.write("        for entity_type in self.ENTITY_TYPES:\n")
    f.write("            if entity_type in self.manifest.entity_counts:\n")
    f.write('                plural_map = {"glossary": "glossaries"}\n')
    f.write("                plural = plural_map.get(entity_type, f\"{entity_type}s\")\n")
    f.write("                file_path = self._package_dir / f\"{plural}.json\"\n")
    f.write("                if not file_path.exists():\n")
    f.write('                    raise ValueError(f"Required entity file missing: {file_path}")\n')
    f.write("\n")
    f.write("        manifest_path = self._package_dir / \"manifest.json\"\n")
    f.write("        if not manifest_path.exists():\n")
    f.write('            raise ValueError(f"Manifest file missing: {manifest_path}")\n')
    f.write("\n")
    f.write("        self._verified = True\n")
    f.write("        return True\n")
    f.write("\n")
    f.write("    def is_verified(self) -> bool:\n")
    f.write('        """Return whether package has been verified."""\n')
    f.write("        return self._verified\n")

print("Part 6 done")