# Write RM_5_7_5_LEGACY_DEPRECATION_REPORT.md - part 2
with open("D:/Python/NTPE/docs/governance/rm5/RM_5_7_5_LEGACY_DEPRECATION_REPORT.md", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('## Migration Mapping')
    f.write('\n')
    f.write('\n')
    f.write('| Legacy Source | v2 Target | Entity Type | Notes |')
    f.write('\n')
    f.write('|---------------|-----------|-------------|-------|')
    f.write('\n')
    f.write('| `memory/character_memory.json` | `characters.json` | character | Direct migration |')
    f.write('\n')
    f.write('| `memory/glossary.json` | `glossaries.json` | glossary | Direct migration |')
    f.write('\n')
    f.write('| `memory/knowledge_base.json` | `characters.json` + `glossaries.json` | character, glossary | Split composite |')
    f.write('\n')
    f.write('| `memory/character_match_dictionary.json` | `characters.json` | character | Aliases merged into entities |')
    f.write('\n')
    f.write('| `memory/character_alias_index.json` | `characters.json` | character | Aliases merged into entities |')
    f.write('\n')
    f.write('| `data/glossary.txt` | `glossaries.json` | glossary | Parsed from flat format |')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## Runtime Boundary')
    f.write('\n')
    f.write('\n')
    f.write('### PROHIBITED for Runtime')
    f.write('\n')
    f.write('\n')
    f.write('- `core.knowledge_generation` (Extractor)')
    f.write('\n')
    f.write('- `core.knowledge_compilation` (Compiler)')
    f.write('\n')
    f.write('- `core.knowledge_review` (Review Engine)')
    f.write('\n')
    f.write('- `core.knowledge_validation` (Validator)')
    f.write('\n')
    f.write('- Any generation pipeline component')
    f.write('\n')
    f.write('\n')
    f.write('### ALLOWED for Runtime')
    f.write('\n')
    f.write('\n')
    f.write('- `core.knowledge.compatibility.KnowledgePackageProvider` (READ-ONLY)')
    f.write('\n')
    f.write('\n')
    f.write('The provider exposes only typed read methods:')
    f.write('\n')
    f.write('\n')
    f.write('```python')
    f.write('\n')
    f.write('provider.get_character(entity_id=None, name=None)')
    f.write('\n')
    f.write('provider.get_glossary(entity_id=None, name=None)')
    f.write('\n')
    f.write('provider.get_scene(entity_id=None, name=None)')
    f.write('\n')
    f.write('provider.get_narrative(entity_id=None, name=None)')
    f.write('\n')
    f.write('provider.get_style(entity_id=None, name=None)')
    f.write('\n')
    f.write('provider.get_entities(entity_type, entity_id=None, name=None)')
    f.write('\n')
    f.write('provider.build_context(entity_types=None)  # For prompt pipeline')
    f.write('\n')
    f.write('provider.verify()  # Integrity check')
    f.write('\n')
    f.write('```')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')

print("Part 2 done")