# Write provider.py - part 3 entity access methods
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('    # === Typed Entity Access Methods (Runtime API) ===')
    f.write('\n')
    f.write('\n')
    f.write('    def get_character(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """Get character entities. Filter by entity_id or name if provided."""')
    f.write('\n')
    f.write('        return self._get_entities("character", entity_id, name)')
    f.write('\n')
    f.write('\n')
    f.write('    def get_glossary(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """Get glossary entities. Filter by entity_id or name if provided."""')
    f.write('\n')
    f.write('        return self._get_entities("glossary", entity_id, name)')
    f.write('\n')
    f.write('\n')
    f.write('    def get_scene(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """Get scene entities. Filter by entity_id or name if provided."""')
    f.write('\n')
    f.write('        return self._get_entities("scene", entity_id, name)')
    f.write('\n')
    f.write('\n')
    f.write('    def get_narrative(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """Get narrative entities. Filter by entity_id or name if provided."""')
    f.write('\n')
    f.write('        return self._get_entities("narrative", entity_id, name)')
    f.write('\n')
    f.write('\n')
    f.write('    def get_style(self, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """Get style entities. Filter by entity_id or name if provided."""')
    f.write('\n')
    f.write('        return self._get_entities("style", entity_id, name)')
    f.write('\n')
    f.write('\n')
    f.write('    def get_entities(self, entity_type: str, entity_id: str | None = None, name: str | None = None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        Generic entity retrieval.')
    f.write('\n')
    f.write('\n')
    f.write('        Args:')
    f.write('\n')
    f.write('            entity_type: One of "character", "glossary", "scene", "narrative", "style"')
    f.write('\n')
    f.write('            entity_id: Optional entity ID filter')
    f.write('\n')
    f.write('            name: Optional name filter')
    f.write('\n')
    f.write('\n')
    f.write('        Returns:')
    f.write('\n')
    f.write('            List of matching entities')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        if entity_type not in self.ENTITY_TYPES:')
    f.write('\n')
    f.write('            raise ValueError(f"Unknown entity type: {entity_type}. Supported: {self.ENTITY_TYPES}")')
    f.write('\n')
    f.write('        return self._get_entities(entity_type, entity_id, name)')
    f.write('\n')
    f.write('\n')
    f.write('    # === Internal Methods ===')
    f.write('\n')
    f.write('\n')
    f.write('    def _get_entities(self, entity_type: str, entity_id: str | None, name: str | None) -> List[Dict[str, Any]]:')
    f.write('\n')
    f.write('        """Internal method to get and filter entities."""')
    f.write('\n')
    f.write('        if entity_type not in self._entity_cache:')
    f.write('\n')
    f.write('            self._entity_cache[entity_type] = self._reader.get_entities(entity_type)')
    f.write('\n')
    f.write('\n')
    f.write('        entities = self._entity_cache[entity_type]')
    f.write('\n')
    f.write('\n')
    f.write('        if entity_id is not None:')
    f.write('\n')
    f.write('            entities = [e for e in entities if e.get("entity_id") == entity_id]')
    f.write('\n')
    f.write('\n')
    f.write('        if name is not None:')
    f.write('\n')
    f.write('            entities = [e for e in entities if e.get("name") == name]')
    f.write('\n')
    f.write('\n')
    f.write('        return entities')
    f.write('\n')

print("Part 3 done")