# Write provider.py - part 7 context building and exports
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("    # === Context Building (for Prompt Pipeline) ===\n")
    f.write("\n")
    f.write("    def build_context(self, entity_types: List[str] | None = None) -> Dict[str, Any]:\n")
    f.write('        """\n')
    f.write("        Build knowledge context for prompt attachment.\n")
    f.write("\n")
    f.write("        Args:\n")
    f.write("            entity_types: Optional list of entity types to include (default: all)\n")
    f.write("\n")
    f.write("        Returns:\n")
    f.write("            Context dictionary compatible with prompt pipeline\n")
    f.write('        """\n')
    f.write("        types = entity_types or self.get_entity_types()\n")
    f.write("        domains: Dict[str, Dict[str, Any]] = {}\n")
    f.write("        items: List[Dict[str, Any]] = []\n")
    f.write("\n")
    f.write("        for entity_type in types:\n")
    f.write("            entities = self._get_entities(entity_type, None, None)\n")
    f.write("            for entity in entities:\n")
    f.write('                key = entity.get("entity_id", entity.get("name", ""))\n')
    f.write("                domains.setdefault(entity_type, {})[key] = entity\n")
    f.write("                items.append(entity)\n")
    f.write("\n")
    f.write("        return {\n")
    f.write('            "type": "knowledge_context",\n')
    f.write('            "version": "rm-5.7.5",\n')
    f.write('            "items": items,\n')
    f.write('            "domains": domains,\n')
    f.write('            "manifest": self.manifest.to_dict(),\n')
    f.write("        }\n")
    f.write("\n")
    f.write("    def attach_to_prompt_package(self, prompt_package: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:\n")
    f.write('        """Attach knowledge context to a prompt package."""\n')
    f.write("        next_package = dict(prompt_package or {})\n")
    f.write("        components = list(next_package.get(\"context_components\", []))\n")
    f.write("        components.append(self.build_context())\n")
    f.write("        next_package[\"context_components\"] = components\n")
    f.write("        return next_package\n")
    f.write("\n\n")
    f.write("def create_provider(package_dir: str | Path, verify_on_load: bool = True) -> KnowledgePackageProvider:\n")
    f.write('    """Convenience function to create a KnowledgePackageProvider."""\n')
    f.write("    return KnowledgePackageProvider(package_dir, verify_on_load=verify_on_load)\n")
    f.write("\n\n")
    f.write("__all__ = [\n")
    f.write('    "KnowledgePackageProvider",\n')
    f.write('    "EntityQuery",\n')
    f.write('    "create_provider",\n')
    f.write("]\n")

print("Part 7 done")