# Write provider.py - part 2 class and init
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write('\n\n')
    f.write('class KnowledgePackageProvider:')
    f.write('\n')
    f.write('    """')
    f.write('\n')
    f.write('    Read-only provider for Frozen Knowledge Packages.')
    f.write('\n')
    f.write('\n')
    f.write('    This is the SINGLE interface Runtime must use.')
    f.write('\n')
    f.write('    All entity access goes through typed methods: get_character(), get_glossary(), etc.')
    f.write('\n')
    f.write('    """')
    f.write('\n')
    f.write('\n')
    f.write('    # Supported entity types')
    f.write('\n')
    f.write('    ENTITY_TYPES = ("character", "glossary", "scene", "narrative", "style")')
    f.write('\n')
    f.write('\n')
    f.write('    def __init__(')
    f.write('\n')
    f.write('        self,')
    f.write('\n')
    f.write('        package_dir: str | Path,')
    f.write('\n')
    f.write('        verify_on_load: bool = True,')
    f.write('\n')
    f.write('        calculator: ChecksumCalculator | None = None,')
    f.write('\n')
    f.write('    ) -> None:')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        Initialize provider with a Frozen Knowledge Package directory.')
    f.write('\n')
    f.write('\n')
    f.write('        Args:')
    f.write('\n')
    f.write('            package_dir: Path to package directory (e.g., artifacts/knowledge_packages/v1)')
    f.write('\n')
    f.write('            verify_on_load: If True, verify package integrity on initialization')
    f.write('\n')
    f.write('            calculator: Checksum calculator (uses default if not provided)')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        self._package_dir = Path(package_dir)')
    f.write('\n')
    f.write('        self._calculator = calculator or DEFAULT_CALCULATOR')
    f.write('\n')
    f.write('        self._reader = create_package_reader(self._package_dir)')
    f.write('\n')
    f.write('        self._package: CompilationPackage | None = None')
    f.write('\n')
    f.write('        self._manifest: CompilationManifest | None = None')
    f.write('\n')
    f.write('        self._entity_cache: Dict[str, List[Dict[str, Any]]] = {}')
    f.write('\n')
    f.write('        self._verified = False')
    f.write('\n')
    f.write('\n')
    f.write('        if verify_on_load:')
    f.write('\n')
    f.write('            self.verify()')
    f.write('\n')
    f.write('\n')
    f.write('    @property')
    f.write('\n')
    f.write('    def package_dir(self) -> Path:')
    f.write('\n')
    f.write('        """Return the package directory path."""')
    f.write('\n')
    f.write('        return self._package_dir')
    f.write('\n')
    f.write('\n')
    f.write('    @property')
    f.write('\n')
    f.write('    def package(self) -> CompilationPackage:')
    f.write('\n')
    f.write('        """Lazy-load the full compilation package."""')
    f.write('\n')
    f.write('        if self._package is None:')
    f.write('\n')
    f.write('            self._package = self._reader.package')
    f.write('\n')
    f.write('        return self._package')
    f.write('\n')
    f.write('\n')
    f.write('    @property')
    f.write('\n')
    f.write('    def manifest(self) -> CompilationManifest:')
    f.write('\n')
    f.write('        """Lazy-load the manifest."""')
    f.write('\n')
    f.write('        if self._manifest is None:')
    f.write('\n')
    f.write('            self._manifest = self._reader.manifest')
    f.write('\n')
    f.write('        return self._manifest')
    f.write('\n')

print("Part 2 done")