# Write legacy_mapper.py - part 1
with open("D:/Python/NTPE/core/knowledge/compatibility/legacy_mapper.py", "w", encoding="utf-8") as f:
    f.write('"""')
    f.write('\n')
    f.write('RM-5.7.5 Legacy Mapper - v1 to v2 mapping.')
    f.write('\n')
    f.write('\n')
    f.write('Maps legacy knowledge paths to Frozen Knowledge Package v2 structure.')
    f.write('\n')
    f.write('"""')
    f.write('\n')
    f.write('\n')
    f.write('from __future__ import annotations')
    f.write('\n')
    f.write('\n')
    f.write('from dataclasses import dataclass')
    f.write('\n')
    f.write('from pathlib import Path')
    f.write('\n')
    f.write('from typing import Any, Dict, List, Optional')
    f.write('\n')
    f.write('\n')
    f.write('@dataclass(frozen=True, slots=True)')
    f.write('\n')
    f.write('class LegacyMapping:')
    f.write('\n')
    f.write('    """Represents a legacy path to v2 package mapping."""')
    f.write('\n')
    f.write('    legacy_path: str')
    f.write('\n')
    f.write('    entity_type: str  # character, glossary, scene, narrative, style')
    f.write('\n')
    f.write('    v2_package_path: str  # e.g., "artifacts/knowledge_packages/v1/characters.json"')
    f.write('\n')
    f.write('    description: str')
    f.write('\n')
    f.write('\n')

print("Part 1 done")