# Write RM_5_7_5_LEGACY_DEPRECATION_REPORT.md - part 3
with open("D:/Python/NTPE/docs/governance/rm5/RM_5_7_5_LEGACY_DEPRECATION_REPORT.md", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('## Verification Requirements')
    f.write('\n')
    f.write('\n')
    f.write('All v2 packages must pass:')
    f.write('\n')
    f.write('\n')
    f.write('1. **Checksum Verification** - Package checksum matches manifest')
    f.write('\n')
    f.write('2. **Manifest Verification** - Entity counts match actual files')
    f.write('\n')
    f.write('3. **Structure Verification** - All required files exist')
    f.write('\n')
    f.write('4. **Deterministic Rebuild** - Package can be rebuilt from source with identical checksum')
    f.write('\n')
    f.write('5. **Compatibility** - Package schema matches current provider expectations')
    f.write('\n')
    f.write('6. **Read-Only Boundary** - No write methods exposed to runtime')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## Deprecation Timeline')
    f.write('\n')
    f.write('\n')
    f.write('| Phase | Date | Action |')
    f.write('\n')
    f.write('|-------|------|--------|')
    f.write('\n')
    f.write('| RM-5.7.5 | 2026-08-03 | Legacy paths documented, v2 package established, compatibility layer active |')
    f.write('\n')
    f.write('| RM-5.8 | TBD | Legacy paths marked with deprecation warnings in code |')
    f.write('\n')
    f.write('| RM-5.9 | TBD | Legacy paths removed from active profiles |')
    f.write('\n')
    f.write('| RM-5.10 | TBD | Legacy files archived to `archive/legacy/` |')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## Verification')
    f.write('\n')
    f.write('\n')
    f.write('Run freeze verification:')
    f.write('\n')
    f.write('\n')
    f.write('```python')
    f.write('\n')
    f.write('from core.knowledge.compatibility import verify_package')
    f.write('\n')
    f.write('\n')
    f.write('report = verify_package("artifacts/knowledge_packages/v1")')
    f.write('\n')
    f.write('print(f"Overall: {\\"PASS\\" if report.overall_passed else \\"FAIL\\"}")')
    f.write('\n')
    f.write('for r in report.results:')
    f.write('\n')
    f.write('    print(f"  {r.check_name}: {\\"OK\\" if r.passed else \\"FAIL\\"} - {r.detail}")')
    f.write('\n')
    f.write('```')
    f.write('\n')
    f.write('\n')
    f.write('---')
    f.write('\n')
    f.write('\n')
    f.write('## Sign-off')
    f.write('\n')
    f.write('\n')
    f.write('- Architecture: | **Baseline established (RM-5.7.0)**')
    f.write('\n')
    f.write('- Capability Audit: | **Complete (RM-5.7.1)**')
    f.write('\n')
    f.write('- Schema & Extraction: | **Complete (RM-5.7.2)**')
    f.write('\n')
    f.write('- Validation: | **Complete (RM-5.7.3)**')
    f.write('\n')
    f.write('- Compilation: | **Complete (RM-5.7.4)**')
    f.write('\n')
    f.write('- **Integration & Legacy Migration: | **Complete (RM-5.7.5)**')
    f.write('\n')
    f.write('\n')
    f.write('**RM-5.7 Series Complete**')
    f.write('\n')

print("Part 3 done")