# Write provider.py - part 4b verification rest, context, exports
with open("D:/Python/NTPE/core/knowledge/compatibility/provider.py", "a", encoding="utf-8") as f:
    f.write('\n')
    f.write('        # Verify manifest matches entities')
    f.write('\n')
    f.write('        for entity_type, count in self.manifest.entity_counts.items():')
    f.write('\n')
    f.write('            actual = self.package.get_entity_count(entity_type)')
    f.write('\n')
    f.write('            if actual != count:')
    f.write('\n')
    f.write('                raise ValueError(')
    f.write('\n')
    f.write('                    f"Manifest entity count mismatch for {entity_type}: "')
    f.write('\n')
    f.write('                    f"manifest={count}, actual={actual}"')
    f.write('\n')
    f.write('                )')
    f.write('\n')
    f.write('\n')
    f.write('        # Verify all required files exist')
    f.write('\n')
    f.write('        for entity_type in self.ENTITY_TYPES:')
    f.write('\n')
    f.write('            if entity_type in self.manifest.entity_counts:')
    f.write('\n')
    f.write('                plural_map = {"glossary": "glossaries"}')
    f.write('\n')
    f.write('                plural = plural_map.get(entity_type, f"{entity_type}s")')
    f.write('\n')
    f.write('                file_path = self._package_dir / f"{plural}.json"')
    f.write('\n')
    f.write('                if not file_path.exists():')
    f.write('\n')
    f.write('                    raise ValueError(f"Required entity file missing: {file_path}")')
    f.write('\n')
    f.write('\n')
    f.write('        manifest_path = self._package_dir / "manifest.json"')
    f.write('\n')
    f.write('        if not manifest_path.exists():')
    f.write('\n')
    f.write('            raise ValueError(f"Manifest file missing: {manifest_path}")')
    f.write('\n')
    f.write('\n')
    f.write('        self._verified = True')
    f.write('\n')
    f.write('        return True')
    f.write('\n')
    f.write('\n')
    f.write('    def is_verified(self) -> bool:')
    f.write('\n')
    f.write('        """Return whether package has been verified."""')
    f.write('\n')
    f.write('        return self._verified')
    f.write('\n')
    f.write('\n')
    f.write('    # === Context Building (for Prompt Pipeline) ===')
    f.write('\n')
    f.write('\n')
    f.write('    def build_context(self, entity_types: List[str] | None = None) -> Dict[str, Any]:')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        Build knowledge context for prompt attachment.')
    f.write('\n')
    f.write('\n')
    f.write('        Args:')
    f.write('\n')
    f.write('            entity_types: Optional list of entity types to include (default: all)')
    f.write('\n')
    f.write('\n')
    f.write('        Returns:')
    f.write('\n')
    f.write('            Context dictionary compatible with prompt pipeline')
    f.write('\n')
    f.write('        """')
    f.write('\n')
    f.write('        types = entity_types or self.get_entity_types()')
    f.write('\n')
    f.write('        domains: Dict[str, Dict[str, Any]] = {}')
    f.write('\n')
    f.write('        items: List[Dict[str, Any]] = []')
    f.write('\n')
    f.write('\n')
    f.write('        for entity_type in types:')
    f.write('\n')
    f.write('            entities = self._get_entities(entity_type, None, None)')
    f.write('\n')
    f.write('            for entity in entities:')
    f.write('\n')
    f.write('                key = entity.get("entity_id", entity.get("name", ""))')
    f.write('\n')
    f.write('                domains.setdefault(entity_type, {})[key] = entity')
    f.write('\n')
    f.write('                items.append(entity)')
    f.write('\n')
    f.write('\n')
    f.write('        return {')
    f.write('\n')
    f.write('            "type": "knowledge_context",')
    f.write('\n')
    f.write('            "version": "rm-5.7.5",')
    f.write('\n')
    f.write('            "items": items,')
    f.write('\n')
    f.write('            "domains": domains,')
    f.write('\n')
    f.write('            "manifest": self.manifest.to_dict(),')
    f.write('\n')
    f.write('        }')
    f.write('\n')
    f.write('\n')
    f.write('    def attach_to_prompt_package(self, prompt_package: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:')
    f.write('\n')
    f.write('        """Attach knowledge context to a prompt package."""')
    f.write('\n')
    f.write('        next_package = dict(prompt_package or {})')
    f.write('\n')
    f.write('        components = list(next_package.get("context_components", []))')
    f.write('\n')
    f.write('        components.append(self.build_context())')
    f.write('\n')
    f.write('        next_package["context_components"] = components')
    f.write('\n')
    f.write('        return next_package')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('def create_provider(package_dir: str | Path, verify_on_load: bool = True) -> KnowledgePackageProvider:')
    f.write('\n')
    f.write('    """Convenience function to create a KnowledgePackageProvider."""')
    f.write('\n')
    f.write('    return KnowledgePackageProvider(package_dir, verify_on_load=verify_on_load)')
    f.write('\n')
    f.write('\n')
    f.write('\n')
    f.write('__all__ = [')
    f.write('\n')
    f.write('    "KnowledgePackageProvider",')
    f.write('\n')
    f.write('    "EntityQuery",')
    f.write('\n')
    f.write('    "create_provider",')
    f.write('\n')
    f.write(']')
    f.write('\n')

print("Part 4b done")