"""NTPE 1.0 Beta Stage-01 Production Runtime manifest."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

VERSION = "ntpe-1.0-beta-stage-01"


def build_production_runtime_manifest(metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    return {
        "name": "ntpe_production_runtime",
        "version": VERSION,
        "stage": "NTPE 1.0 Beta Stage-01",
        "components": [
            "RuntimeHost",
            "RuntimeScheduler",
            "RuntimeSessionManager",
            "RuntimeCheckpointStore",
            "RuntimeRecoveryManager",
            "RuntimeMetrics",
            "RuntimeTelemetry",
        ],
        "capabilities": [
            "production_host",
            "job_scheduler",
            "session_lock",
            "checkpoint",
            "resume",
            "recovery",
            "metrics",
            "telemetry",
            "knowledge_runtime_bridge",
        ],
        "metadata": dict(metadata or {}),
    }


def get_canonical_artifact_root(root: str | Path) -> Path:
    """Return the canonical artifacts root directory."""
    return Path(root).resolve() / "artifacts"


def get_te_v7_stage_path(root: str | Path, stage: str) -> Path:
    """Return the canonical path for a TE-v7 stage artifact directory.

    Args:
        root: Project root directory
        stage: Stage identifier (e.g., "te_v7_stage09", "te_v7_stage109")

    Returns:
        Path to the stage artifact directory
    """
    return get_canonical_artifact_root(root) / stage


def get_te_v7_artifact_path(root: str | Path, stage: str, artifact_name: str) -> Path:
    """Return the canonical path for a specific TE-v7 artifact file.

    Args:
        root: Project root directory
        stage: Stage identifier (e.g., "te_v7_stage09")
        artifact_name: Name of the artifact file

    Returns:
        Path to the artifact file
    """
    return get_te_v7_stage_path(root, stage) / artifact_name


# TIC (Translation Intelligence Corpus) artifact paths
def get_tic_batch_artifact_path(root: str | Path, batch: str, artifact_name: str) -> Path:
    """Return the canonical path for a TIC batch artifact file.

    Args:
        root: Project root directory
        batch: Batch identifier (e.g., "tic_batch1", "tic_batch2", "tic_batch3")
        artifact_name: Name of the artifact file

    Returns:
        Path to the artifact file
    """
    return get_canonical_artifact_root(root) / batch / artifact_name


def get_tic_batch_path(root: str | Path, batch: str) -> Path:
    """Return the canonical path for a TIC batch artifact directory.

    Args:
        root: Project root directory
        batch: Batch identifier (e.g., "tic_batch1", "tic_batch2", "tic_batch3")

    Returns:
        Path to the batch artifact directory
    """
    return get_canonical_artifact_root(root) / batch


# TE-v7 Stage artifact name constants
TE_V7_STAGE09_BASELINE = "TE_V7_STAGE09_BASELINE.json"
TE_V7_STAGE09_CANDIDATE = "TE_V7_STAGE09_CANDIDATE.json"
TE_V7_STAGE09_COMPARISON = "TE_V7_STAGE09_COMPARISON.json"
TE_V7_STAGE09_READINESS = "TE_V7_STAGE09_READINESS.json"

TE_V7_STAGE081_PRODUCTION_ACTIVATION_POLICY = "TE_V7_STAGE081_PRODUCTION_ACTIVATION_POLICY.json"
TE_V7_STAGE082_PROFILE_AWARE_CONTEXT_BUDGET = "TE_V7_STAGE082_PROFILE_AWARE_CONTEXT_BUDGET.json"
TE_V7_STAGE083_ADAPTIVE_CONTEXT_STRATEGY_SELECTION = "TE_V7_STAGE083_ADAPTIVE_CONTEXT_STRATEGY_SELECTION.json"

TE_V7_STAGE075_CANARY_AB_QUALITY_VALIDATION = "TE_V7_STAGE075_CANARY_AB_QUALITY_VALIDATION.json"
TE_V7_STAGE06_CANARY_PRODUCTION_VALIDATION = "TE_V7_STAGE06_CANARY_PRODUCTION_VALIDATION.json"
TE_V7_STAGE04_PRODUCTION_SHADOW_VALIDATION = "TE_V7_STAGE04_PRODUCTION_SHADOW_VALIDATION.json"

TE_V7_STAGE109_REAL_PROVIDER_PREFLIGHT = "TE_V7_STAGE109_REAL_PROVIDER_PREFLIGHT.json"
TE_V7_STAGE108_FAKE_TRANSPORT_FREEZE = "TE_V7_STAGE108_FAKE_TRANSPORT_FREEZE.json"

TE_V7_STAGE1010_SINGLE_REAL_INVOCATION = "TE_V7_STAGE1010_SINGLE_REAL_INVOCATION.json"
TE_V7_STAGE1010_TRANSLATION_REVIEW = "TE_V7_STAGE1010_TRANSLATION_REVIEW.txt"
TE_V7_STAGE10101_CONTROLLED_RETRY = "TE_V7_STAGE10101_CONTROLLED_RETRY.json"
TE_V7_STAGE10101_TRANSLATION_REVIEW = "TE_V7_STAGE10101_TRANSLATION_REVIEW.txt"

# TE-v7.1 Stage artifact name constants
TE_V71_STAGE111_TRANSLATION_DEFECTS = "TE_V71_STAGE111_TRANSLATION_DEFECTS.json"
TE_V71_STAGE112_QUALITY_METRICS = "TE_V71_STAGE112_QUALITY_METRICS.json"
TE_V71_STAGE112_QUALITY_SUMMARY = "TE_V71_STAGE112_QUALITY_SUMMARY.json"
TE_V71_STAGE113_REVIEW = "TE_V71_STAGE113_REVIEW.json"
TE_V71_STAGE113_REVIEW_DEFECTS = "TE_V71_STAGE113_REVIEW_DEFECTS.json"
TE_V71_STAGE113_REVIEW_METRICS = "TE_V71_STAGE113_REVIEW_METRICS.json"
TE_V71_STAGE113_REVIEW_SUMMARY = "TE_V71_STAGE113_REVIEW_SUMMARY.json"
TE_V71_STAGE114_PROMPT_IMPROVEMENT_PLAN = "TE_V71_STAGE114_PROMPT_IMPROVEMENT_PLAN.json"
TE_V71_STAGE115_REVIEW_DECISION_CONTRACT = "TE_V71_STAGE115_REVIEW_DECISION_CONTRACT.json"
TE_V71_STAGE116_GOLDEN_CORPUS_GOVERNANCE = "TE_V71_STAGE116_GOLDEN_CORPUS_GOVERNANCE.json"
TE_V71_STAGE117_QUALITY_FRAMEWORK_INTEGRATION = "TE_V71_STAGE117_QUALITY_FRAMEWORK_INTEGRATION.json"
TE_V71_STAGE118_TRANSLATION_QUALITY_FRAMEWORK_FREEZE = "TE_V71_STAGE118_TRANSLATION_QUALITY_FRAMEWORK_FREEZE.json"

# TE-v7.2 Stage artifact name constants
TE_V72_STAGE121_EVIDENCE_BASED_PROMPT_QUALITY_CANDIDATE = "TE_V72_STAGE121_EVIDENCE_BASED_PROMPT_QUALITY_CANDIDATE.json"
TE_V72_STAGE121_MANUAL_REVIEW_TEMPLATE = "TE_V72_STAGE121_MANUAL_REVIEW_TEMPLATE.json"
TE_V72_STAGE121_PROVIDER_EXECUTION_PACKAGE = "TE_V72_STAGE121_PROVIDER_EXECUTION_PACKAGE.json"

TE_V72_STAGE122_AB_EXECUTION_PACKAGE = "TE_V72_STAGE122_AB_EXECUTION_PACKAGE.json"
TE_V72_STAGE122_MANUAL_AB_REVIEW = "TE_V72_STAGE122_MANUAL_AB_REVIEW.json"
TE_V72_STAGE122_BASELINE_PROMPT_PROFILE = "baseline_prompt_profile.json"
TE_V72_STAGE122_BASELINE_REQUEST = "baseline_request.json"
TE_V72_STAGE122_BASELINE_RESPONSE = "baseline_response.json"
TE_V72_STAGE122_CANDIDATE_PROMPT_PROFILE = "candidate_prompt_profile.json"
TE_V72_STAGE122_CANDIDATE_REQUEST = "candidate_request.json"
TE_V72_STAGE122_CANDIDATE_RESPONSE = "candidate_response.json"

TE_V72_STAGE1221_CONTROLLED_AB_EXECUTION = "TE_V72_STAGE1221_CONTROLLED_AB_EXECUTION.json"
TE_V72_STAGE1221_MANUAL_AB_REVIEW = "TE_V72_STAGE1221_MANUAL_AB_REVIEW.json"
TE_V72_STAGE1221_BASELINE_EXECUTION_METADATA = "baseline/execution_metadata.json"
TE_V72_STAGE1221_BASELINE_PROMPT_PROFILE = "baseline/prompt_profile.json"
TE_V72_STAGE1221_BASELINE_RAW_RESPONSE = "baseline/raw_response.json"
TE_V72_STAGE1221_BASELINE_REQUEST = "baseline/request.json"
TE_V72_STAGE1221_BASELINE_TRANSLATION = "baseline/translation.txt"
TE_V72_STAGE1221_CANDIDATE_EXECUTION_METADATA = "candidate/execution_metadata.json"
TE_V72_STAGE1221_CANDIDATE_PROMPT_PROFILE = "candidate/prompt_profile.json"
TE_V72_STAGE1221_CANDIDATE_RAW_RESPONSE = "candidate/raw_response.json"
TE_V72_STAGE1221_CANDIDATE_REQUEST = "candidate/request.json"
TE_V72_STAGE1221_CANDIDATE_TRANSLATION = "candidate/translation.txt"

TE_V72_STAGE1222_INDEPENDENT_PAIR_EXECUTION = "TE_V72_STAGE1222_INDEPENDENT_PAIR_EXECUTION.json"
TE_V72_STAGE1222_MANUAL_AB_REVIEW = "TE_V72_STAGE1222_MANUAL_AB_REVIEW.json"
TE_V72_STAGE1222_BASELINE_EXECUTION_METADATA = "baseline/execution_metadata.json"
TE_V72_STAGE1222_BASELINE_PROMPT_PROFILE = "baseline/prompt_profile.json"
TE_V72_STAGE1222_BASELINE_RAW_RESPONSE = "baseline/raw_response.json"
TE_V72_STAGE1222_BASELINE_REQUEST = "baseline/request.json"
TE_V72_STAGE1222_BASELINE_TRANSLATION = "baseline/translation.txt"
TE_V72_STAGE1222_CANDIDATE_EXECUTION_METADATA = "candidate/execution_metadata.json"
TE_V72_STAGE1222_CANDIDATE_PROMPT_PROFILE = "candidate/prompt_profile.json"
TE_V72_STAGE1222_CANDIDATE_RAW_RESPONSE = "candidate/raw_response.json"
TE_V72_STAGE1222_CANDIDATE_REQUEST = "candidate/request.json"
TE_V72_STAGE1222_CANDIDATE_TRANSLATION = "candidate/translation.txt"

TE_V72_STAGE1223_MANUAL_AB_REVIEW = "TE_V72_STAGE1223_MANUAL_AB_REVIEW.json"
TE_V72_STAGE1223_MINIMAL_EXCERPT_AB_EXECUTION = "TE_V72_STAGE1223_MINIMAL_EXCERPT_AB_EXECUTION.json"
TE_V72_STAGE1223_SOURCE_EXCERPT_FREEZE = "TE_V72_STAGE1223_SOURCE_EXCERPT_FREEZE.json"
TE_V72_STAGE1223_BASELINE_EXECUTION_METADATA = "baseline/execution_metadata.json"
TE_V72_STAGE1223_BASELINE_PROMPT_PROFILE = "baseline/prompt_profile.json"
TE_V72_STAGE1223_BASELINE_RAW_RESPONSE = "baseline/raw_response.json"
TE_V72_STAGE1223_BASELINE_REQUEST = "baseline/request.json"
TE_V72_STAGE1223_BASELINE_TRANSLATION = "baseline/translation.txt"
TE_V72_STAGE1223_CANDIDATE_EXECUTION_METADATA = "candidate/execution_metadata.json"
TE_V72_STAGE1223_CANDIDATE_PROMPT_PROFILE = "candidate/prompt_profile.json"
TE_V72_STAGE1223_CANDIDATE_RAW_RESPONSE = "candidate/raw_response.json"
TE_V72_STAGE1223_CANDIDATE_REQUEST = "candidate/request.json"
TE_V72_STAGE1223_CANDIDATE_TRANSLATION = "candidate/translation.txt"

TE_V72_STAGE1256_PROMPT_VERIFICATION_CANARY = "artifacts/te_v72_stage1256_prompt_verification_canary"
TE_V72_STAGE1256_PROMPT_VERIFICATION_CANARY_ACTIVATION_DECISION = "activation_decision.json"
TE_V72_STAGE1256_PROMPT_VERIFICATION_CANARY_AUTHORIZATION_CLAIM = "authorization_claim.json"
TE_V72_STAGE1256_PROMPT_VERIFICATION_CANARY_EXECUTION_SUMMARY = "execution_summary.json"
TE_V72_STAGE1256_PROMPT_VERIFICATION_CANARY_FAILURE_RECORD = "failure_record.json"
TE_V72_STAGE1256_PROMPT_VERIFICATION_CANARY_PREFLIGHT = "preflight.json"

TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION = "artifacts/te_v72_stage1256a_claim_safe_corpus_binding_remediation"
TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION_CLAIM_LIFECYCLE_VALIDATION = "claim_lifecycle_validation.json"
TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION_CORPUS_IDENTITY_CONTRACT = "corpus_identity_contract.json"
TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION_CORPUS_RESOLUTION_VALIDATION = "corpus_resolution_validation.json"
TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION_HISTORICAL_STAGE1256_SEAL = "historical_stage1256_seal.json"
TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION_PREFLIGHT_ORDERING_VALIDATION = "preflight_ordering_validation.json"
TE_V72_STAGE1256A_CLAIM_SAFE_CORPUS_BINDING_REMEDIATION_REMEDIATION_SUMMARY = "remediation_summary.json"

TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY = "artifacts/te_v72_stage1257_prompt_verification_canary"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_AUTHORIZATION_CLAIM = "authorization_claim.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_BASELINE_REQUEST = "baseline_request.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_BASELINE_RESPONSE = "baseline_response.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_CORPUS_RESOLUTION = "corpus_resolution.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_EXECUTION_SUMMARY = "execution_summary.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_LATENCY_COMPARISON = "latency_comparison.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_MANUAL_REVIEW_PACKAGE = "manual_review_package.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_PREFLIGHT = "preflight.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_PROVISIONAL_ACTIVATION_DECISION = "provisional_activation_decision.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_REQUEST_PLAN = "request_plan.json"
TE_V72_STAGE1257_PROMPT_VERIFICATION_CANARY_STRUCTURAL_VALIDATION = "structural_validation.json"

TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING = "artifacts/te_v72_stage1257a_execution_evidence_sealing"
TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING_CLAIM_LIFECYCLE = "claim_lifecycle.json"
TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING_FINAL_ACTIVATION_DECISION = "final_activation_decision.json"
TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING_HISTORICAL_EXECUTION_SEAL = "historical_execution_seal.json"
TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING_REQUEST_BUDGET_ACCOUNTING = "request_budget_accounting.json"
TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING_SEALING_SUMMARY = "sealing_summary.json"
TE_V72_STAGE1257A_EXECUTION_EVIDENCE_SEALING_TEST_STATE_ISOLATION = "test_state_isolation.json"

TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY = "artifacts/te_v72_stage1258_candidate_structural_verification_canary"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_ACTIVATION_CONTRACT = "activation_contract.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_AUTHORIZATION_CLAIM = "authorization_claim.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_CANDIDATE_REQUEST = "candidate_request.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_CANDIDATE_RESPONSE = "candidate_response.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_CLAIM_CONTRACT = "claim_contract.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_CORPUS_RESOLUTION = "corpus_resolution.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_EXECUTION_SUMMARY = "execution_summary.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_FINAL_ACTIVATION_DECISION = "final_activation_decision.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_PREFLIGHT = "preflight.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_PREFLIGHT_TEMPLATE = "preflight_template.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_PREPARATION_SUMMARY = "preparation_summary.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_REQUEST_PLAN = "request_plan.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_STRUCTURAL_VALIDATION = "structural_validation.json"
TE_V72_STAGE1258_CANDIDATE_STRUCTURAL_VERIFICATION_CANARY_STRUCTURAL_VALIDATION_CONTRACT = "structural_validation_contract.json"

TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING = "artifacts/te_v72_stage1258a_candidate_structural_failure_sealing"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_CLAIM_LIFECYCLE = "claim_lifecycle.json"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_HISTORICAL_EXECUTION_SEAL = "historical_execution_seal.json"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_NAME_RESOLUTION_TRACE = "name_resolution_trace.json"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_PROMPT_NAME_MAPPING_EVIDENCE = "prompt_name_mapping_evidence.json"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_REMEDIATION_DECISION = "remediation_decision.json"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_SEALING_SUMMARY = "sealing_summary.json"
TE_V72_STAGE1258A_CANDIDATE_STRUCTURAL_FAILURE_SEALING_STRUCTURAL_FAILURE_CLASSIFICATION = "structural_failure_classification.json"

TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION = "artifacts/te_v72_stage1259_name_resolution_contract_remediation"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_ACTIVATION_CONTRACT = "activation_contract.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_BUDGET_EVIDENCE = "budget_evidence.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_CONFLICT_RESOLUTION_CONTRACT = "conflict_resolution_contract.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_MAPPING_ELIGIBILITY_EVIDENCE = "mapping_eligibility_evidence.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_NAME_RESOLUTION_CONTRACT = "name_resolution_contract.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_OUTPUT_VALIDATION_EXTENSION = "output_validation_extension.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_PREPARATION_SUMMARY = "preparation_summary.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_PROMPT_RENDERING_CANDIDATE = "prompt_rendering_candidate.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_SOURCE_INVENTORY = "source_inventory.json"
TE_V72_STAGE1259_NAME_RESOLUTION_CONTRACT_REMEDIATION_UNRESOLVED_NAME_EVIDENCE = "unresolved_name_evidence.json"


__all__ = [
    "VERSION",
    "build_production_runtime_manifest",
    "get_canonical_artifact_root",
    "get_te_v7_stage_path",
    "get_te_v7_artifact_path",
    "get_tic_batch_artifact_path",
    "get_tic_batch_path",
    "TE_V7_STAGE09_BASELINE",
    "TE_V7_STAGE09_CANDIDATE",
    "TE_V7_STAGE09_COMPARISON",
    "TE_V7_STAGE09_READINESS",
    "TE_V7_STAGE081_PRODUCTION_ACTIVATION_POLICY",
    "TE_V7_STAGE082_PROFILE_AWARE_CONTEXT_BUDGET",
    "TE_V7_STAGE083_ADAPTIVE_CONTEXT_STRATEGY_SELECTION",
    "TE_V7_STAGE075_CANARY_AB_QUALITY_VALIDATION",
    "TE_V7_STAGE06_CANARY_PRODUCTION_VALIDATION",
    "TE_V7_STAGE04_PRODUCTION_SHADOW_VALIDATION",
    "TE_V7_STAGE109_REAL_PROVIDER_PREFLIGHT",
    "TE_V7_STAGE108_FAKE_TRANSPORT_FREEZE",
    "TE_V7_STAGE1010_SINGLE_REAL_INVOCATION",
    "TE_V7_STAGE10101_CONTROLLED_RETRY",
    "TE_V7_STAGE10101_TRANSLATION_REVIEW",
    "TE_V71_STAGE111_TRANSLATION_DEFECTS",
    "TE_V71_STAGE112_QUALITY_METRICS",
    "TE_V71_STAGE112_QUALITY_SUMMARY",
    "TE_V71_STAGE113_REVIEW",
    "TE_V71_STAGE113_REVIEW_DEFECTS",
    "TE_V71_STAGE113_REVIEW_METRICS",
    "TE_V71_STAGE113_REVIEW_SUMMARY",
    "TE_V71_STAGE114_PROMPT_IMPROVEMENT_PLAN",
    "TE_V71_STAGE115_REVIEW_DECISION_CONTRACT",
    "TE_V71_STAGE116_GOLDEN_CORPUS_GOVERNANCE",
    "TE_V71_STAGE117_QUALITY_FRAMEWORK_INTEGRATION",
    "TE_V71_STAGE118_TRANSLATION_QUALITY_FRAMEWORK_FREEZE",
    "TE_V72_STAGE121_EVIDENCE_BASED_PROMPT_QUALITY_CANDIDATE",
    "TE_V72_STAGE121_MANUAL_REVIEW_TEMPLATE",
    "TE_V72_STAGE121_PROVIDER_EXECUTION_PACKAGE",
    "TE_V72_STAGE122_AB_EXECUTION_PACKAGE",
    "TE_V72_STAGE122_MANUAL_AB_REVIEW",
    "TE_V72_STAGE122_BASELINE_PROMPT_PROFILE",
    "TE_V72_STAGE122_BASELINE_REQUEST",
    "TE_V72_STAGE122_BASELINE_RESPONSE",
    "TE_V72_STAGE122_CANDIDATE_PROMPT_PROFILE",
    "TE_V72_STAGE122_CANDIDATE_REQUEST",
    "TE_V72_STAGE122_CANDIDATE_RESPONSE",
    "TE_V72_STAGE1221_CONTROLLED_AB_EXECUTION",
    "TE_V72_STAGE1221_MANUAL_AB_REVIEW",
    "TE_V72_STAGE1221_BASELINE_EXECUTION_METADATA",
    "TE_V72_STAGE1221_BASELINE_PROMPT_PROFILE",
    "TE_V72_STAGE1221_BASELINE_RAW_RESPONSE",
    "TE_V72_STAGE1221_BASELINE_REQUEST",
    "TE_V72_STAGE1221_BASELINE_TRANSLATION",
    "TE_V72_STAGE1221_CANDIDATE_EXECUTION_METADATA",
    "TE_V72_STAGE1221_CANDIDATE_PROMPT_PROFILE",
    "TE_V72_STAGE1221_CANDIDATE_RAW_RESPONSE",
    "TE_V72_STAGE1221_CANDIDATE_REQUEST",
    "TE_V72_STAGE1221_CANDIDATE_TRANSLATION",
    "TE_V72_STAGE1222_INDEPENDENT_PAIR_EXECUTION",
    "TE_V72_STAGE1222_MANUAL_AB_REVIEW",
    "TE_V72_STAGE1222_BASELINE_EXECUTION_METADATA",
    "TE_V72_STAGE1222_BASELINE_PROMPT_PROFILE",
    "TE_V72_STAGE1222_BASELINE_RAW_RESPONSE",
    "TE_V72_STAGE1222_BASELINE_REQUEST",
    "TE_V72_STAGE1222_BASELINE_TRANSLATION",
    "TE_V72_STAGE1222_CANDIDATE_EXECUTION_METADATA",
    "TE_V72_STAGE1222_CANDIDATE_PROMPT_PROFILE",
    "TE_V72_STAGE1222_CANDIDATE_RAW_RESPONSE",
    "TE_V72_STAGE1222_CANDIDATE_REQUEST",
    "TE_V72_STAGE1222_CANDIDATE_TRANSLATION",
    "TE_V72_STAGE1223_MANUAL_AB_REVIEW",
    "TE_V72_STAGE1223_MINIMAL_EXCERPT_AB_EXECUTION",
    "TE_V72_STAGE1223_SOURCE_EXCERPT_FREEZE",
    "TE_V72_STAGE1223_BASELINE_EXECUTION_METADATA",
    "TE_V72_STAGE1223_BASELINE_PROMPT_PROFILE",
    "TE_V72_STAGE1223_BASELINE_RAW_RESPONSE",
    "TE_V72_STAGE1223_BASELINE_REQUEST",
    "TE_V72_STAGE1223_BASELINE_TRANSLATION",
    "TE_V72_STAGE1223_CANDIDATE_EXECUTION_METADATA",
    "TE_V72_STAGE1223_CANDIDATE_PROMPT_PROFILE",
    "TE_V72_STAGE1223_CANDIDATE_RAW_RESPONSE",
    "TE_V72_STAGE1223_CANDIDATE_REQUEST",
    "TE_V72_STAGE1223_CANDIDATE_TRANSLATION",
]
